"use client";

import { useMemo, useState } from "react";

type View = "overview" | "devices" | "library" | "backups" | "protection";
type Device = {
  id:string; name:string; kind:string; bus:string; location:string; capacity:string; used:number;
  free:string; filesystem:string; health:string; operational:string; contents:string;
  status:"Ready"|"Needs attention"|"Waiting for media"|"Protected"; tone:"green"|"amber"|"blue";
  disk?:string; partitions?:string; protection:string; warning?:string;
};

const devices:Device[] = [
  {id:"nvme",name:"Samsung 970 EVO Plus",kind:"NVMe SSD",bus:"NVMe",location:"Disk 3 · C:",capacity:"1.0 TB",used:94,free:"64.2 GB",filesystem:"NTFS",health:"Healthy",operational:"Online / OK",contents:"Windows system and applications",status:"Ready",tone:"blue",disk:"System + boot disk",partitions:"EFI · Reserved · C: · Recovery",protection:"Not backed up by Legacy Doctor",warning:"System, EFI, reserved, and recovery partitions must remain unchanged."},
  {id:"g-drive",name:"Samsung 860 EVO",kind:"SATA SSD",bus:"SATA",location:"Disk 0 · G:",capacity:"1.0 TB",used:26,free:"745.1 GB",filesystem:"NTFS",health:"Healthy",operational:"Online / OK",contents:"Mounted fixed storage",status:"Ready",tone:"green",disk:"Data disk",partitions:"1 basic partition",protection:"Not yet catalogued"},
  {id:"s-drive",name:"ST2000DM008",kind:"SATA HDD",bus:"SATA",location:"Disk 1 · S:",capacity:"2.0 TB",used:29,free:"1.42 TB",filesystem:"NTFS",health:"Healthy",operational:"Online / OK",contents:"Mounted fixed storage",status:"Ready",tone:"green",disk:"Data disk",partitions:"1 basic partition",protection:"Not yet catalogued"},
  {id:"p-drive",name:"Samsung 870 QVO",kind:"SATA SSD",bus:"SATA",location:"Disk 2 · P:",capacity:"2.0 TB",used:73,free:"544.2 GB",filesystem:"NTFS",health:"Healthy",operational:"Online / OK",contents:"Mounted fixed storage",status:"Ready",tone:"green",disk:"Data disk",partitions:"1 basic partition",protection:"Not yet catalogued"},
  {id:"ipod",name:"Apple iPod Shuffle",kind:"MP3 player",bus:"USB",location:"Disk 4 · E:",capacity:"1.0 GB",used:1,free:"1.013 GB",filesystem:"FAT32",health:"Warning",operational:"Full Repair Needed",contents:"10 files · 401,619 bytes",status:"Protected",tone:"amber",disk:"Removable MBR device",partitions:"1 FAT32 partition",protection:"10 of 10 files SHA-256 verified",warning:"Preserved before repair. Do not format or repair until a raw image and restore test exist."},
  {id:"iphone",name:"Apple iPhone",kind:"Mobile device",bus:"USB · PTP",location:"Portable device · no drive letter",capacity:"Not reported",used:0,free:"Not reported",filesystem:"PTP / WPD",health:"Connected",operational:"Device Manager: OK",contents:"Full library not accessible through mounted storage",status:"Needs attention",tone:"amber",disk:"Not a block-storage disk",partitions:"Not exposed to Windows",protection:"Full backup adapter not implemented",warning:"A drive letter is not expected for an iPhone. Apple-device backup support is still required."},
  {id:"optical",name:"MATSHITA DVD-RAM UJ8C0",kind:"Optical drive",bus:"USB",location:"Drive D:",capacity:"No media",used:0,free:"No media",filesystem:"No disc mounted",health:"Healthy",operational:"Waiting for media",contents:"No disc inserted",status:"Waiting for media",tone:"amber",disk:"USB optical device",partitions:"None until media is inserted",protection:"Nothing to back up"},
];

const files = [
  ["iPod_Control/iTunes/iTunesControl",393216,"a6619f482fee91a315f76cdcd8705d39b6ce11077c435ccc696142e130c27762"],
  ["iPod_Control/iTunes/iTunesDB",3672,"252a2e24e4b65cce8c05b70ae77bf1f8d666058bc631c2d2a92fd6d9ec16c487"],
  ["iPod_Control/iTunes/iTunesPrefs",1232,"300141b0482c7b6a00dd147190462799c5bf637cc3fbf9811001fd8fe8d2f8bc"],
  ["iPod_Control/iTunes/iTunesPrefs.plist",2359,"959c3b29aa24f7d207398af13691c3e16f06fb1d20359740bb80cfd8769c34ca"],
  ["iPod_Control/iTunes/iTunesPState",32,"43cb1b58d4bafd873326afc85edea4392c2c0f16a97fefc76684e83f957a6d91"],
  ["iPod_Control/iTunes/iTunesSD",18,"4e97957dcf5f54f6b5ce4b9992a13e213e06540de02991efd5b4df44306255f7"],
  ["iPod_Control/iTunes/iTunesShuffle",996,"dadff70bc66b0edd3c8b5daf23f49ce931603f847785f212ca9cdf9bd9f632cf"],
  ["iPod_Control/iTunes/iTunesStats",6,"b0f66adc83641586656866813fd9dd0b8ebb63796075661ba45d1aa8089e1d44"],
  ["System Volume Information/IndexerVolumeGuid",76,"b43bd513b6c2652b3de3274cad79035465e40b0b5ea1501a84aa063ccd6332de"],
  ["System Volume Information/WPSettings.dat",12,"f15450c61987f1bbb172db2a0868cd83983ed7a259e664f59a6cef57a057cd46"],
] as const;

function Icon({name}:{name:string}) {
  const paths:Record<string,React.ReactNode>={
    grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    drive:<><path d="M4 6h16v12H4z"/><path d="M7 14h.01M17 14h.01"/></>,library:<><path d="M4 19V5M9 19V5M14 19V5M19 19V8"/><path d="M2 19h20"/></>,
    history:<><path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/></>,shield:<><path d="M12 3 5 6v5c0 4.6 2.9 8.2 7 10 4.1-1.8 7-5.4 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/></>,
    settings:<><circle cx="12" cy="12" r="3"/><path d="M19 14.5V9.5l-2-.7-.7-1.7.9-1.9-3.5-2-1.4 1.5h-2L8.8 3.2l-3.5 2 .9 1.9-.7 1.7-2 .7v5l2 .7.7 1.7-.9 1.9 3.5 2 1.4-1.5h2l1.5 1.5 3.5-2-.9-1.9.7-1.7 2-.7Z"/></>,
  }; return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>;
}

function bytes(value:number){ if(value<1024)return `${value} B`; return `${(value/1024).toFixed(value>10000?0:1)} KB`; }

export default function Home(){
  const [view,setView]=useState<View>("overview");
  const [selected,setSelected]=useState(devices[4]);
  const [managed,setManaged]=useState<Device|null>(null);
  const [query,setQuery]=useState("");
  const [skipDuplicates,setSkipDuplicates]=useState(true);
  const [chosen,setChosen]=useState<Set<string>>(new Set());
  const [notice,setNotice]=useState("Verified hardware snapshot · 2026-08-18 19:29 UTC · read-only source");
  const filtered=useMemo(()=>devices.filter(d=>`${d.name} ${d.kind} ${d.location}`.toLowerCase().includes(query.toLowerCase())),[query]);
  const selectedBytes=files.filter(f=>chosen.has(f[0])).reduce((sum,f)=>sum+f[1],0);
  const nav=(next:View)=>{setView(next);location.hash=next;};
  const toggleFile=(path:string)=>setChosen(current=>{const next=new Set(current);if(next.has(path)){next.delete(path);}else{next.add(path);}return next;});
  const duplicateToggle=()=>{const next=!skipDuplicates;setSkipDuplicates(next);setChosen(next?new Set():new Set(files.map(f=>f[0])));};
  const gated=(action:string)=>setNotice(`${action} remains disabled until a verified restore point and explicit approval exist`);

  return <main className="shell">
    <aside className="sidebar"><div className="brand"><span className="brandmark">LD</span><div><strong>Legacy Doctor</strong><small>Evidence-backed operations</small></div></div>
      <nav aria-label="Main navigation">
        <button className={view==="overview"?"active":""} onClick={()=>nav("overview")}><Icon name="grid"/>Overview</button>
        <button className={view==="devices"?"active":""} onClick={()=>nav("devices")}><Icon name="drive"/>Devices <span>7</span></button>
        <button className={view==="library"?"active":""} onClick={()=>nav("library")}><Icon name="library"/>Library</button>
        <button className={view==="backups"?"active":""} onClick={()=>nav("backups")}><Icon name="history"/>Backup selection</button>
        <button className={view==="protection"?"active":""} onClick={()=>nav("protection")}><Icon name="shield"/>Protection</button>
      </nav>
      <div className="sidebar-bottom"><div className="agent"><i/><div><b>Proof mode</b><small>Real snapshot · source read-only</small></div></div><button><Icon name="settings"/>Settings</button></div>
    </aside>

    <section className="content">
      <header><div><p className="eyebrow">{view.toUpperCase()}</p><h1>{view==="overview"?"Your connected legacy media.":view==="devices"?"Device and machine inspector.":view==="library"?"Verified media library.":view==="backups"?"Choose exactly what gets saved.":"Cryptographic protection status."}</h1><p>{view==="backups"?"Review every file, skip known duplicates, and preserve an auditable decision.":"Real hardware evidence from this computer. No destructive action is implied."}</p></div><div className="header-actions"><button className="ghost" onClick={()=>setNotice("Snapshot loaded · 5 disks · 7 volumes · iPod and iPhone connected")}>↻&nbsp; View scan result</button><button className="primary" onClick={()=>nav("backups")}>＋&nbsp; Plan backup</button></div></header>
      <div className="notice"><span>●</span>{notice}<button onClick={()=>setNotice("Verified hardware snapshot · 2026-08-18 19:29 UTC · read-only source")}>×</button></div>

      {view==="overview"&&<>
        <section className="metrics"><article><div className="metric-icon green">⌁</div><div><small>CONNECTED DEVICES</small><strong>7</strong><p>5 disks · iPhone · optical</p></div></article><article><div className="metric-icon blue">◫</div><div><small>CATALOGUED BYTES</small><strong>401,619</strong><p>10 iPod files hashed</p></div></article><article><div className="metric-icon purple">↺</div><div><small>VERIFIED BACKUPS</small><strong>1</strong><p>10 of 10 hashes matched</p></div></article><article><div className="metric-icon amber">△</div><div><small>NEEDS ATTENTION</small><strong>3</strong><p>iPod · iPhone adapter · empty DVD</p></div></article></section>
        <section className="overview-grid"><div className="panel machine-card"><div className="panel-head compact"><div><h2>This machine</h2><p>Host specifications captured from Windows.</p></div><span className="status green"><i/>Detected</span></div><div className="spec-grid"><div><small>COMPUTER</small><b>MSI MS-7C95</b><p>PRO B550M-VC WIFI</p></div><div><small>PROCESSOR</small><b>AMD Ryzen 7 5800X</b><p>8 cores · 16 threads · 3.8 GHz</p></div><div><small>MEMORY</small><b>64 GB RAM</b><p>68.6 GB reported bytes</p></div><div><small>GRAPHICS</small><b>NVIDIA GeForce RTX 4060</b><p>Windows display adapter</p></div><div><small>OPERATING SYSTEM</small><b>Windows 11 Home</b><p>64-bit · build 26200</p></div><div><small>STORAGE PROFILE</small><b>6.0 TB visible</b><p>NVMe · SATA SSD · SATA HDD · USB</p></div></div></div>
          <div className="panel proof-card"><div className="panel-head compact"><div><h2>Latest preservation proof</h2><p>Apple iPod Shuffle · E:</p></div><span className="status green"><i/>Verified</span></div><div className="proof-ring"><strong>10/10</strong><small>HASHES MATCHED</small></div><dl><div><dt>Source bytes</dt><dd>401,619</dd></div><div><dt>Copied bytes</dt><dd>401,619</dd></div><div><dt>Catalog SHA-256</dt><dd className="mono">0888bfce…0f80eee</dd></div><div><dt>Source writes</dt><dd>None</dd></div></dl><button className="primary wide" onClick={()=>nav("library")}>Inspect backed-up files</button></div></section>
        <DeviceSection filtered={filtered} query={query} setQuery={setQuery} selected={selected} setSelected={setSelected} setManaged={setManaged}/>
      </>}

      {view==="devices"&&<><section className="panel machine-summary"><div><p className="eyebrow">HOST CLASSIFICATION</p><h2>Desktop workstation · MSI B550 · AMD Ryzen</h2><p>Likely storage: four internal fixed disks, one removable iPod disk, one optical drive. Portable device: one iPhone over USB/PTP.</p></div><div className="summary-chips"><span>NVMe × 1</span><span>SATA × 3</span><span>USB storage × 1</span><span>WPD × 2</span><span>Optical × 1</span></div></section><DeviceSection filtered={filtered} query={query} setQuery={setQuery} selected={selected} setSelected={setSelected} setManaged={setManaged}/></>}

      {view==="library"&&<section className="panel library-page"><div className="panel-head"><div><h2>iPod verified library snapshot</h2><p>Every row is tied to the catalog receipt and verified destination copy.</p></div><div className="receipt-pill">Receipt · executed_verified</div></div><div className="library-stats"><div><small>FILES</small><b>10</b></div><div><small>BYTES</small><b>401,619</b></div><div><small>APPLE LIBRARY</small><b>8</b></div><div><small>GENERIC METADATA</small><b>2</b></div><div><small>MUSIC TRACKS</small><b>0</b></div></div><FileTable selectable={false} chosen={chosen} toggleFile={toggleFile}/><div className="truth-note"><b>What this means</b><p>The iPod currently contains Apple control/library data, but no audio-track files were found. Legacy Doctor preserves those bytes without interpreting or rewriting them.</p></div></section>}

      {view==="backups"&&<section className="backup-layout"><div className="panel backup-files"><div className="panel-head"><div><h2>Backup selection · Apple iPod Shuffle</h2><p>Choose files explicitly. Known copies are compared by content hash, not filename.</p></div><label className="duplicate-toggle"><input type="checkbox" checked={skipDuplicates} onChange={duplicateToggle}/><span/>Skip verified duplicates</label></div><div className="selection-bar"><div><b>{chosen.size}</b><small> selected</small></div><div><b>{files.length-chosen.size}</b><small> skipped</small></div><div><b>{bytes(selectedBytes)}</b><small> new bytes</small></div><button onClick={()=>setChosen(new Set(files.map(f=>f[0])))}>Select all</button><button onClick={()=>setChosen(new Set())}>Clear</button></div><FileTable selectable chosen={chosen} toggleFile={toggleFile}/></div>
        <aside className="panel plan-summary"><p className="eyebrow">BACKUP PLAN</p><h2>{chosen.size?`${chosen.size} files selected`:"Nothing new to copy"}</h2><p>{skipDuplicates?"All ten source hashes already match verified destination copies.":"Duplicate skipping is off; selected files would be saved again."}</p><dl><div><dt>Selected bytes</dt><dd>{bytes(selectedBytes)}</dd></div><div><dt>Verified duplicates</dt><dd>{files.length-chosen.size}</dd></div><div><dt>Source writes</dt><dd>Never</dd></div><div><dt>Collision policy</dt><dd>Fail closed</dd></div><div><dt>Partial-copy policy</dt><dd>Rollback</dd></div></dl><button className="primary wide" disabled={!chosen.size} onClick={()=>setNotice(`Backup plan staged · ${chosen.size} files · ${bytes(selectedBytes)} · execution requires local approval`)}>Create backup plan</button><button className="ghost wide" onClick={()=>nav("library")}>Review existing backup</button><small className="fine-print">Selections are interface state only until the local executor receives an explicit destination and approval.</small></aside></section>}

      {view==="protection"&&<><section className="crypto-grid"><article className="panel crypto proven"><span>✓</span><small>INTEGRITY</small><h2>SHA-256 proven</h2><p>Every backed-up iPod file was hashed before and after copying. All 10 source and destination hashes match.</p></article><article className="panel crypto pending"><span>◇</span><small>CONFIDENTIALITY</small><h2>Encryption not configured</h2><p>The backup bytes are integrity-verified but not encrypted by Legacy Doctor today. The dashboard does not call them encrypted.</p></article><article className="panel crypto pending"><span>⌁</span><small>AUTHENTICITY</small><h2>Signing not configured</h2><p>Receipts are structured and hashed, but they are not yet signed by an identity or hardware-backed key.</p></article></section><section className="panel evidence-chain"><div><p className="eyebrow">BYTE PROTECTION CHAIN</p><h2>What was cryptographically checked</h2></div><ol><li><b>Discover</b><span>Enumerate source paths and exact byte lengths.</span></li><li><b>Hash source</b><span>Compute SHA-256 before copying.</span></li><li><b>Copy partially</b><span>Write to a temporary destination name.</span></li><li><b>Verify temporary</b><span>Hash and compare before promotion.</span></li><li><b>Promote + reverify</b><span>Move into place; hash source and destination again.</span></li><li><b>Receipt</b><span>Record decisions, byte counts, hashes, and outcome.</span></li></ol></section><section className="workbench panel"><div><p className="eyebrow">WRITE OPERATIONS</p><h2>Still safety-gated.</h2><p>Integrity proof for a file backup does not authorize formatting, raw imaging, cloning, or restore.</p></div><div className="work-actions"><button onClick={()=>gated("Assign drive letter")}><b>＋</b><span>Assign drive letter<small>System partitions excluded</small></span></button><button onClick={()=>gated("Format media")}><b>▦</b><span>Format media<small>Destructive · unavailable</small></span></button><button onClick={()=>gated("Disk image")}><b>◫</b><span>Create disk image<small>Not yet proven on hardware</small></span></button><button onClick={()=>gated("Restore")}><b>↺</b><span>Restore<small>Not yet proven on hardware</small></span></button></div></section></>}
      <footer><span>Legacy Doctor · local-first media preservation</span><span><i/>Verified local snapshot · destructive actions disabled</span></footer>
    </section>

    {/* The backdrop intentionally closes this modal on pointer selection. */}
    {/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions */}
    {managed&&<div className="drawer-backdrop" role="presentation" onMouseDown={()=>setManaged(null)}><aside className="device-drawer" role="dialog" aria-modal="true" aria-label={`${managed.name} details`} onMouseDown={e=>e.stopPropagation()}><button className="drawer-close" onClick={()=>setManaged(null)} aria-label="Close device details">×</button><div className="drawer-hero"><span className={`device-symbol large ${managed.tone}`}>{managed.kind.includes("Mobile")?"▯":managed.kind.includes("Optical")?"◉":"▰"}</span><div><p className="eyebrow">REAL DEVICE INFORMATION</p><h2>{managed.name}</h2><p>{managed.kind} · {managed.bus}</p></div></div>{managed.warning&&<div className="warning-box"><b>Attention</b><p>{managed.warning}</p></div>}<div className="capacity-card"><div><small>CAPACITY</small><b>{managed.capacity}</b></div><div><small>FREE</small><b>{managed.free}</b></div>{managed.used>0&&<i><em style={{width:`${managed.used}%`}}/></i>}<p>{managed.used}% used</p></div><dl className="detail-list"><div><dt>Location</dt><dd>{managed.location}</dd></div><div><dt>Health</dt><dd>{managed.health}</dd></div><div><dt>Operational state</dt><dd>{managed.operational}</dd></div><div><dt>Filesystem / protocol</dt><dd>{managed.filesystem}</dd></div><div><dt>Disk role</dt><dd>{managed.disk}</dd></div><div><dt>Partitions</dt><dd>{managed.partitions}</dd></div><div><dt>Known contents</dt><dd>{managed.contents}</dd></div><div><dt>Protection</dt><dd>{managed.protection}</dd></div></dl><button className="primary wide" onClick={()=>{setSelected(managed);setManaged(null);nav("backups")}}>Plan backup</button><button className="ghost wide" onClick={()=>gated("Device repair")}>Repair options</button></aside></div>}
  </main>;
}

function DeviceSection({filtered,query,setQuery,selected,setSelected,setManaged}:{filtered:Device[];query:string;setQuery:(v:string)=>void;selected:Device;setSelected:(d:Device)=>void;setManaged:(d:Device)=>void}){
  return <section className="panel devices"><div className="panel-head"><div><h2>Connected devices</h2><p>Physical storage and portable devices visible in the verified snapshot.</p></div><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a device..."/></label></div><div className="device-layout"><div className="device-list"><div className="table-head"><span>DEVICE</span><span>CONNECTED AT</span><span>CAPACITY</span><span>STATE</span></div>{filtered.map(device=><button key={device.id} className={`device-row ${selected.id===device.id?"selected":""}`} onClick={()=>setSelected(device)}><span className={`device-symbol ${device.tone}`}>{device.kind.includes("Mobile")?"▯":device.kind.includes("Optical")?"◉":"▰"}</span><span className="device-name"><b>{device.name}</b><small>{device.kind} · {device.bus}</small></span><span className="location"><b>{device.location}</b><small>{device.contents}</small></span><span className="capacity"><b>{device.capacity}</b>{device.used>0&&<i><em style={{width:`${device.used}%`}}/></i>}<small>{device.free} free</small></span><span className={`status ${device.tone}`}><i/>{device.status}</span></button>)}</div><aside className="device-detail"><div className="detail-top"><span className={`device-symbol large ${selected.tone}`}>▰</span><div><small>SELECTED DEVICE</small><h3>{selected.name}</h3><p>{selected.kind} · {selected.bus}</p></div></div><dl><div><dt>Visible at</dt><dd>{selected.location}</dd></div><div><dt>Health</dt><dd>{selected.health}</dd></div><div><dt>Free space</dt><dd>{selected.free}</dd></div><div><dt>Protection</dt><dd>{selected.protection}</dd></div></dl><button className="primary wide" onClick={()=>setManaged(selected)}>Manage device</button></aside></div></section>;
}

function FileTable({selectable,chosen,toggleFile}:{selectable:boolean;chosen:Set<string>;toggleFile:(p:string)=>void}){
  return <div className="file-table"><div className="file-head"><span>{selectable?"SELECT":"STATE"}</span><span>PATH</span><span>SIZE</span><span>CONTENT HASH</span><span>BACKUP</span></div>{files.map(file=>{const selected=chosen.has(file[0]);return <label className={`file-row ${selected?"chosen":""}`} key={file[0]}>{selectable?<input type="checkbox" checked={selected} onChange={()=>toggleFile(file[0])}/>:<span className="hash-ok">✓</span>}<span><b>{file[0].split("/").pop()}</b><small>{file[0]}</small></span><span>{bytes(file[1])}</span><code title={file[2]}>{file[2].slice(0,12)}…</code><span className="duplicate-badge">Hash match</span></label>})}</div>;
}
