param([Parameter(Mandatory=$true)][string]$RepoRoot)
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
function Die([string]$Code,[string]$Detail){throw($Code+":"+$Detail)}
function Require([bool]$Condition,[string]$Code,[string]$Detail){if(-not$Condition){Die $Code $Detail}}
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Force -Path $Path|Out-Null}}
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $RepoRoot "scripts\storage\_lib_ld_receipts_v1.ps1");$base=Join-Path $RepoRoot "proofs\selftest\storage03_post_copy_verifier";$allowed=[IO.Path]::GetFullPath((Join-Path $RepoRoot "proofs\selftest")).TrimEnd("\")+"\";$full=[IO.Path]::GetFullPath($base);Require $full.StartsWith($allowed,[StringComparison]::OrdinalIgnoreCase) "FIXTURE_ESCAPE" $full;if(Test-Path -LiteralPath $full){Remove-Item -LiteralPath $full -Recurse -Force};$source=Join-Path $full "source";$dest=Join-Path $full "destination";EnsureDir $source;EnsureDir $dest;[IO.File]::WriteAllBytes((Join-Path $source "music.m4a"),[Text.Encoding]::UTF8.GetBytes("verifier-fixture"))
$backup=Join-Path $RepoRoot "scripts\media\ld_mounted_media_backup_v1.ps1";$args=@("-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File",$backup,"-RepoRoot",$RepoRoot,"-SourceRoot",$source,"-DestinationRoot",$dest,"-MaxFiles","10","-MaxBytes","1048576","-Execute");$out=& powershell.exe @args;if($LASTEXITCODE-ne0){Die "BACKUP_EXIT" ([string]$LASTEXITCODE)};$child=LDREC-ReadReceiptFromOutput $out "ld.media.mounted_backup.receipt.v1" (Join-Path $RepoRoot "schemas");$pathLine=@($out|Where-Object{([string]$_)-match"^MOUNTED_MEDIA_BACKUP_PATH:"})|Select-Object -First 1;Require ($null-ne$pathLine) "BACKUP_PATH_MISSING" "";$backupPath=([string]$pathLine).Substring(([string]$pathLine).IndexOf(":")+1).Trim();Require (Test-Path -LiteralPath $backupPath -PathType Leaf) "BACKUP_RECEIPT_MISSING" $backupPath
$verifier=Join-Path $RepoRoot "scripts\storage\ld_storage03_post_copy_verifier_v1.ps1";$verifyOut=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $verifier -RepoRoot $RepoRoot -BackupReceiptPath $backupPath;if($LASTEXITCODE-ne0){Die "VERIFIER_EXIT" ([string]$LASTEXITCODE)};$verified=LDREC-ReadReceiptFromOutput $verifyOut "ld.device.storage03_post_copy_verifier.receipt.v1" (Join-Path $RepoRoot "schemas");Require ([bool]$verified.ok) "VERIFY_NOT_OK" "";Require (([string]$verified.verification_status)-eq"verified") "VERIFY_NOT_VERIFIED" "";Require ([int]$verified.verified_row_count-eq1) "VERIFY_ROW_COUNT" ""
[IO.File]::WriteAllBytes((Join-Path $source "music.m4a"),[Text.Encoding]::UTF8.GetBytes("verifier-fixture-source-stable"));$tampered=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $verifier -RepoRoot $RepoRoot -BackupReceiptPath $backupPath;if($LASTEXITCODE-ne0){Die "TAMPER_VERIFY_EXIT" ([string]$LASTEXITCODE)};$blocked=LDREC-ReadReceiptFromOutput $tampered "ld.device.storage03_post_copy_verifier.receipt.v1" (Join-Path $RepoRoot "schemas");Require (-not[bool]$blocked.ok) "TAMPER_NOT_BLOCKED" "";Require ([bool](@($blocked.blockers|Where-Object{([string]$_)-match"SOURCE_HASH_MISMATCH"}).Count -gt 0)) "SOURCE_TAMPER_REASON" ""
Write-Output "PASS: independent verifier rehashed source and destination bytes from the receipt";Write-Output "PASS: source tampering was rejected without writing destination bytes";Write-Output "SELFTEST_LD_STORAGE03_POST_COPY_VERIFIER_OK"
