param([Parameter(Mandatory=$true)][string]$RepoRoot)
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
function Require([bool]$Condition,[string]$Code){if(-not$Condition){throw $Code}}
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Force -Path $Path|Out-Null}}
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $RepoRoot "scripts\storage\_lib_ld_receipts_v1.ps1");$schemaDir=Join-Path $RepoRoot "schemas";$base=Join-Path $RepoRoot "proofs\selftest\backup_scheduler";$allowed=[IO.Path]::GetFullPath((Join-Path $RepoRoot "proofs\selftest")).TrimEnd("\")+"\";$full=[IO.Path]::GetFullPath($base);Require ($full.StartsWith($allowed,[StringComparison]::OrdinalIgnoreCase)) "FIXTURE_ESCAPE";if(Test-Path -LiteralPath $full){Remove-Item -LiteralPath $full -Recurse -Force};EnsureDir $full
function Run([string]$Script,[string]$Schema,[string[]]$ExtraArgs){$args=@("-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File",$Script,"-RepoRoot",$RepoRoot);$args+=@($ExtraArgs);$out=& powershell.exe @args;if($LASTEXITCODE-ne0){throw("CHILD_EXIT_NONZERO:"+$Script)};return (LDREC-ReadReceiptFromOutput $out $Schema $schemaDir)}
$vault=Join-Path $full "vault";$state=Join-Path $full "state";$source=Join-Path $full "connected-device";EnsureDir $source;[IO.File]::WriteAllText((Join-Path $source "song.mp3"),"scheduler fixture",[Text.UTF8Encoding]::new($false))
$identity=LDREC-HexSha256TextLf "scheduler-device";$setup=Run (Join-Path $RepoRoot "scripts\storage\ld_backup_one_click_setup_v1.ps1") "ld.backup.one_click_setup.receipt.v1" @("-DestinationRoot",$vault,"-ProfileLabel","Scheduler Vault","-BackupMode","file_backup","-DeviceName","Connected MP3","-DeviceIdentitySha256",$identity,"-BackupId","scheduled-001","-MinFreeBytes","0","-OwnedTestFixture","-Execute");Require ([bool]$setup.ok) "SETUP_FAILED";$manifest=Join-Path ([string]$setup.workspace_root) "workspace.v1.json"
$job=Run (Join-Path $RepoRoot "scripts\storage\ld_backup_job_v1.ps1") "ld.backup.job.receipt.v1" @("-StateRoot",$state,"-Action","enqueue","-SourceRoot",$source,"-WorkspaceManifestPath",$manifest,"-Schedule","on_connect","-MaxFiles","10","-MaxBytes","1048576","-Execute");Require ([bool]$job.ok) "JOB_ENQUEUE_FAILED";$jobPath=[string]$job.rows[0].job_path
$scheduler=Join-Path $RepoRoot "scripts\storage\ld_backup_scheduler_v1.ps1";$plan=Run $scheduler "ld.backup.scheduler.receipt.v1" @("-StateRoot",$state,"-Action","plan","-ConnectedSourceRoot",$source,"-NowUtc","2026-09-14T12:00:00Z");Require ([bool]$plan.ok) "PLAN_FAILED";Require ([int]$plan.eligible_count-eq1) "PLAN_NOT_ELIGIBLE";Require (([string]$plan.rows[0].eligibility_reason)-eq"connected_not_run") "PLAN_REASON_BAD"
$dry=Run $scheduler "ld.backup.scheduler.receipt.v1" @("-StateRoot",$state,"-Action","run","-ConnectedSourceRoot",$source,"-NowUtc","2026-09-14T12:00:00Z");Require ([bool]$dry.ok) "DRY_RUN_FAILED";Require (([string]$dry.execution_status)-eq"dry_run_ready") "DRY_RUN_STATUS_BAD";Require (([string]$dry.rows[0].run_status)-eq"dry_run_ready") "DRY_RUN_ROW_BAD";Require (-not(Test-Path -LiteralPath (Join-Path ([string]$setup.payload_path) "song.mp3") -PathType Leaf)) "DRY_RUN_WROTE"
$executed=Run $scheduler "ld.backup.scheduler.receipt.v1" @("-StateRoot",$state,"-Action","run","-ConnectedSourceRoot",$source,"-NowUtc","2026-09-14T12:00:00Z","-Execute");Require ([bool]$executed.ok) "SCHEDULED_RUN_FAILED";Require (([string]$executed.execution_status)-eq"executed") "SCHEDULED_STATUS_BAD";Require (([string]$executed.rows[0].run_status)-eq"succeeded") "SCHEDULED_ROW_BAD";Require (Test-Path -LiteralPath (Join-Path ([string]$setup.payload_path) "song.mp3") -PathType Leaf) "SCHEDULED_FILE_MISSING"
$after=Run $scheduler "ld.backup.scheduler.receipt.v1" @("-StateRoot",$state,"-Action","plan","-ConnectedSourceRoot",$source,"-NowUtc","2026-09-14T12:00:01Z");Require ([bool]$after.ok) "AFTER_PLAN_FAILED";Require ([int]$after.eligible_count-eq0) "ON_CONNECT_RERUN_NOT_BLOCKED";Require (([string]$after.rows[0].eligibility_reason)-eq"already_run_for_connection") "AFTER_REASON_BAD"
$tampered=Get-Content -LiteralPath $jobPath -Raw|ConvertFrom-Json;$tampered.source_root=Join-Path $full "different-device";$tamperedJson=$tampered|ConvertTo-Json -Depth 20 -Compress;[IO.File]::WriteAllText($jobPath,$tamperedJson,[Text.UTF8Encoding]::new($false));$blocked=Run $scheduler "ld.backup.scheduler.receipt.v1" @("-StateRoot",$state,"-Action","plan","-ConnectedSourceRoot",$source,"-NowUtc","2026-09-14T12:00:02Z");Require (-not[bool]$blocked.ok) "TAMPERED_JOB_NOT_BLOCKED";Require (@($blocked.blockers)-contains"JOB_SPEC_IDENTITY_MISMATCH") "TAMPER_REASON_BAD"
Write-Output "PASS: on-connect jobs are planned only when the connected source matches"
Write-Output "PASS: scheduler dry-run performs no destination writes"
Write-Output "PASS: scheduler executes through the existing verified backup runner"
Write-Output "PASS: completed on-connect jobs are not replayed on the next poll"
Write-Output "PASS: tampered job identity fails closed before execution"
Write-Output "SELFTEST_LD_BACKUP_SCHEDULER_OK"
