param([Parameter(Mandatory=$true)][string]$RepoRoot)
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
function Require([bool]$Condition,[string]$Code){if(-not$Condition){throw $Code}}
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Force -Path $Path|Out-Null}}
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $RepoRoot "scripts\storage\_lib_ld_receipts_v1.ps1");$schemaDir=Join-Path $RepoRoot "schemas";$base=Join-Path $RepoRoot "proofs\selftest\backup_backend_lifecycle";$allowed=[IO.Path]::GetFullPath((Join-Path $RepoRoot "proofs\selftest")).TrimEnd("\")+"\";$full=[IO.Path]::GetFullPath($base);Require ($full.StartsWith($allowed,[StringComparison]::OrdinalIgnoreCase)) "FIXTURE_ESCAPE";if(Test-Path -LiteralPath $full){Remove-Item -LiteralPath $full -Recurse -Force};EnsureDir $full
function Run([string]$Script,[string]$Schema,[string[]]$ExtraArgs){$childArgs=@("-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File",$Script,"-RepoRoot",$RepoRoot);$childArgs+=@($ExtraArgs);$out=& powershell.exe @childArgs;if($LASTEXITCODE-ne0){throw("CHILD_EXIT_NONZERO:"+$Script)};return (LDREC-ReadReceiptFromOutput $out $Schema $schemaDir)}
$vault=Join-Path $full "vault";$state=Join-Path $full "state";$source=Join-Path $full "source";$upload=Join-Path $full "upload";EnsureDir $source;EnsureDir (Join-Path $source "music");EnsureDir $upload;[IO.File]::WriteAllText((Join-Path $source "music\track.txt"),"fixture music bytes",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllBytes((Join-Path $source "save.rom"),[byte[]](0..127))
$identity=LDREC-HexSha256TextLf "fixture-legacy-device";$setup=Run (Join-Path $RepoRoot "scripts\storage\ld_backup_one_click_setup_v1.ps1") "ld.backup.one_click_setup.receipt.v1" @("-DestinationRoot",$vault,"-ProfileLabel","Fixture Vault","-BackupMode","file_backup","-DeviceName","Fixture MP3 Player","-DeviceIdentitySha256",$identity,"-BackupId","backup-001","-MinFreeBytes","0","-OwnedTestFixture","-Execute");Require ([bool]$setup.ok) "SETUP_FAILED";$manifest=Join-Path ([string]$setup.workspace_root) "workspace.v1.json"
$registryScript=Join-Path $RepoRoot "scripts\storage\ld_backend_destination_registry_v1.ps1";$regDry=Run $registryScript "ld.backend.destination_registry.receipt.v1" @("-StateRoot",$state,"-Action","register","-DestinationRoot",$vault);Require (([string]$regDry.execution_status)-eq"dry_run_ready") "REGISTRY_DRY_NOT_READY";Require (-not(Test-Path -LiteralPath $state)) "REGISTRY_DRY_WROTE";$reg=Run $registryScript "ld.backend.destination_registry.receipt.v1" @("-StateRoot",$state,"-Action","register","-DestinationRoot",$vault,"-Execute");Require (([string]$reg.execution_status)-eq"registered") "REGISTRY_NOT_WRITTEN";$verify=Run $registryScript "ld.backend.destination_registry.receipt.v1" @("-StateRoot",$state,"-Action","verify");Require ([bool]$verify.ok) "REGISTRY_VERIFY_FAILED"
$jobScript=Join-Path $RepoRoot "scripts\storage\ld_backup_job_v1.ps1";$enqueue=Run $jobScript "ld.backup.job.receipt.v1" @("-StateRoot",$state,"-Action","enqueue","-SourceRoot",$source,"-WorkspaceManifestPath",$manifest,"-Schedule","on_connect","-MaxFiles","20","-MaxBytes","1048576","-Execute");Require ([bool]$enqueue.ok) "JOB_ENQUEUE_FAILED";$jobId=[string]$enqueue.rows[0].job_id;$repeat=Run $jobScript "ld.backup.job.receipt.v1" @("-StateRoot",$state,"-Action","enqueue","-SourceRoot",$source,"-WorkspaceManifestPath",$manifest,"-Schedule","on_connect","-MaxFiles","20","-MaxBytes","1048576","-Execute");Require (([string]$repeat.execution_status)-eq"already_enqueued") "JOB_NOT_IDEMPOTENT";$run=Run $jobScript "ld.backup.job.receipt.v1" @("-StateRoot",$state,"-Action","run","-JobId",$jobId,"-Execute");Require (([string]$run.execution_status)-eq"succeeded") "JOB_RUN_FAILED";Require (Test-Path -LiteralPath (Join-Path ([string]$setup.payload_path) "music\track.txt") -PathType Leaf) "BACKUP_FILE_MISSING";Require ((LDREC-HexSha256File (Join-Path $source "save.rom"))-ceq(LDREC-HexSha256File (Join-Path ([string]$setup.payload_path) "save.rom"))) "BACKUP_HASH_MISMATCH"
$uploadScript=Join-Path $RepoRoot "scripts\storage\ld_verified_file_upload_v1.ps1";$artifact=Join-Path ([string]$setup.payload_path) "save.rom";$artifactHash=LDREC-HexSha256File $artifact;$uploadDry=Run $uploadScript "ld.upload.filesystem.receipt.v1" @("-SourceFile",$artifact,"-ExpectedSha256",$artifactHash,"-UploadRoot",$upload);Require (([string]$uploadDry.execution_status)-eq"dry_run_ready") "UPLOAD_DRY_NOT_READY";$uploaded=Run $uploadScript "ld.upload.filesystem.receipt.v1" @("-SourceFile",$artifact,"-ExpectedSha256",$artifactHash,"-UploadRoot",$upload,"-Execute");Require (([string]$uploaded.execution_status)-eq"uploaded_verified") "UPLOAD_FAILED";Require ((LDREC-HexSha256File ([string]$uploaded.target_path))-ceq$artifactHash) "UPLOAD_HASH_MISMATCH";$bad=Run $uploadScript "ld.upload.filesystem.receipt.v1" @("-SourceFile",$artifact,"-ExpectedSha256",("0"*64),"-UploadRoot",$upload,"-TargetName","bad.rom","-Execute");Require (-not[bool]$bad.ok) "BAD_UPLOAD_NOT_BLOCKED";Require (-not(Test-Path -LiteralPath (Join-Path $upload "bad.rom"))) "BAD_UPLOAD_WROTE"
$retentionScript=Join-Path $RepoRoot "scripts\storage\ld_backup_retention_v1.ps1";$plan=Run $retentionScript "ld.backup.retention.receipt.v1" @("-DestinationRoot",$vault,"-Action","plan","-KeepLast","1","-OlderThanDays","0");Require ([bool]$plan.ok) "RETENTION_PLAN_FAILED";Require ([int]$plan.row_count-eq1) "RETENTION_PLAN_COUNT_BAD";$manifestHash=LDREC-HexSha256File $manifest;$qDry=Run $retentionScript "ld.backup.retention.receipt.v1" @("-DestinationRoot",$vault,"-Action","quarantine","-WorkspaceManifestPath",$manifest,"-ExpectedManifestSha256",$manifestHash);Require (([string]$qDry.execution_status)-eq"dry_run_ready") "QUARANTINE_DRY_NOT_READY";Require (Test-Path -LiteralPath ([string]$setup.workspace_root)) "QUARANTINE_DRY_MOVED";$q=Run $retentionScript "ld.backup.retention.receipt.v1" @("-DestinationRoot",$vault,"-Action","quarantine","-WorkspaceManifestPath",$manifest,"-ExpectedManifestSha256",$manifestHash,"-Execute");Require (([string]$q.execution_status)-eq"quarantined_verified") "QUARANTINE_FAILED";Require (-not(Test-Path -LiteralPath ([string]$setup.workspace_root))) "QUARANTINE_SOURCE_REMAINED";Require (Test-Path -LiteralPath ([string]$q.quarantine_path) -PathType Container) "QUARANTINE_TARGET_MISSING"
Write-Output "PASS: destination registry re-verifies managed profiles"
Write-Output "PASS: persistent on-connect job runs the hash-verified mounted-media copier"
Write-Output "PASS: filesystem/network upload adapter refuses unverified bytes"
Write-Output "PASS: retention plans are read-only and clearing is reversible quarantine"
Write-Output "SELFTEST_LD_BACKUP_BACKEND_LIFECYCLE_OK"
