param([Parameter(Mandatory=$true)][string]$RepoRoot)
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
function Die([string]$Code,[string]$Detail){throw($Code+":"+$Detail)}
function Require([bool]$Condition,[string]$Code,[string]$Detail){if(-not$Condition){Die $Code $Detail}}
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Force -Path $Path|Out-Null}}
function Write-Lf([string]$Path,[string]$Text){EnsureDir(Split-Path -Parent $Path);$t=($Text-replace"`r`n","`n")-replace"`r","`n";if(-not$t.EndsWith("`n")){$t+="`n"};[IO.File]::WriteAllText($Path,$t,[Text.UTF8Encoding]::new($false))}
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $RepoRoot "scripts\storage\_lib_ld_receipts_v1.ps1");$base=Join-Path $RepoRoot "proofs\selftest\backup_set_seal";$allowed=[IO.Path]::GetFullPath((Join-Path $RepoRoot "proofs\selftest")).TrimEnd("\")+"\";$full=[IO.Path]::GetFullPath($base);Require $full.StartsWith($allowed,[StringComparison]::OrdinalIgnoreCase) "FIXTURE_ESCAPE" $full;if(Test-Path -LiteralPath $full){Remove-Item -LiteralPath $full -Recurse -Force};$workspace=Join-Path $full "workspace";$payload=Join-Path $workspace "payload";foreach($d in @($payload,(Join-Path $workspace "metadata"),(Join-Path $workspace "receipts"),(Join-Path $workspace "logs"),(Join-Path $payload "roms"))){EnsureDir $d};[IO.File]::WriteAllBytes((Join-Path $payload "music.m4a"),[Text.Encoding]::UTF8.GetBytes("seal-music"));[IO.File]::WriteAllBytes((Join-Path $payload "roms\game.nes"),[Text.Encoding]::UTF8.GetBytes("seal-rom"))
$identity=LDREC-HexSha256TextLf "seal-fixture-device";$manifest=[ordered]@{schema="ld.backup.workspace_manifest.v1";event_type="ld.backup.workspace_manifest.v1";destination_profile_id="fixture-profile";backup_mode="file_backup";backup_id="seal-001";device_name="Seal Fixture";device_identity_sha256=$identity;workspace_root=$workspace;payload_path=$payload;metadata_path=(Join-Path $workspace "metadata");receipts_path=(Join-Path $workspace "receipts");logs_path=(Join-Path $workspace "logs");source_writes_allowed=$false;created_utc=[DateTime]::UtcNow.ToString("o")};$manifestPath=Join-Path $workspace "workspace.v1.json";Write-Lf $manifestPath (LDREC-ToCanonJson $manifest)
$sealScript=Join-Path $RepoRoot "scripts\storage\ld_backup_set_seal_v1.ps1";$verifyScript=Join-Path $RepoRoot "scripts\storage\ld_backup_set_verify_v1.ps1";$schemaDir=Join-Path $RepoRoot "schemas";$dry=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $sealScript -RepoRoot $RepoRoot -WorkspaceManifestPath $manifestPath;if($LASTEXITCODE-ne0){Die "SEAL_DRY_EXIT" ([string]$LASTEXITCODE)};$dryReceipt=LDREC-ReadReceiptFromOutput $dry "ld.backup.set.seal.receipt.v1" $schemaDir;Require (([string]$dryReceipt.verification_status)-eq"dry_run_ready") "SEAL_DRY_STATUS" ([string]$dryReceipt.verification_status);Require (-not(Test-Path -LiteralPath (Join-Path $workspace "receipts\backup-set.seal.v1.json") -PathType Leaf)) "SEAL_DRY_WROTE" ""
$sealed=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $sealScript -RepoRoot $RepoRoot -WorkspaceManifestPath $manifestPath -Execute;if($LASTEXITCODE-ne0){Die "SEAL_EXEC_EXIT" ([string]$LASTEXITCODE)};$sealedReceipt=LDREC-ReadReceiptFromOutput $sealed "ld.backup.set.seal.receipt.v1" $schemaDir;Require ([bool]$sealedReceipt.ok) "SEAL_NOT_OK" "";Require (([string]$sealedReceipt.verification_status)-eq"sealed_verified") "SEAL_STATUS" ([string]$sealedReceipt.verification_status);$sealPath=Join-Path $workspace "receipts\backup-set.seal.v1.json";Require (Test-Path -LiteralPath $sealPath -PathType Leaf) "SEAL_MISSING" ""
$verified=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $verifyScript -RepoRoot $RepoRoot -SealPath $sealPath -WorkspaceRoot $workspace;if($LASTEXITCODE-ne0){Die "VERIFY_EXIT" ([string]$LASTEXITCODE)};$v=LDREC-ReadReceiptFromOutput $verified "ld.backup.set.verify.receipt.v1" $schemaDir;Require ([bool]$v.ok) "VERIFY_NOT_OK" "";Require (([string]$v.verification_status)-eq"verified") "VERIFY_STATUS" ""
$portable=Join-Path $full "portable-copy";Copy-Item -LiteralPath $workspace -Destination $portable -Recurse -Force;$pv=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $verifyScript -RepoRoot $RepoRoot -SealPath (Join-Path $portable "receipts\backup-set.seal.v1.json") -WorkspaceRoot $portable;if($LASTEXITCODE-ne0){Die "PORTABLE_VERIFY_EXIT" ([string]$LASTEXITCODE)};$pvr=LDREC-ReadReceiptFromOutput $pv "ld.backup.set.verify.receipt.v1" $schemaDir;Require ([bool]$pvr.ok) "PORTABLE_VERIFY_NOT_OK" ""
[IO.File]::WriteAllBytes((Join-Path $portable "payload\music.m4a"),[Text.Encoding]::UTF8.GetBytes("tampered"));$tampered=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $verifyScript -RepoRoot $RepoRoot -SealPath (Join-Path $portable "receipts\backup-set.seal.v1.json") -WorkspaceRoot $portable;if($LASTEXITCODE-ne0){Die "TAMPER_VERIFY_EXIT" ([string]$LASTEXITCODE)};$tr=LDREC-ReadReceiptFromOutput $tampered "ld.backup.set.verify.receipt.v1" $schemaDir;Require (-not[bool]$tr.ok) "TAMPER_NOT_BLOCKED" "";Require ([bool](@($tr.blockers|Where-Object{([string]$_)-match"HASH_MISMATCH"}).Count -gt 0)) "TAMPER_REASON" "";Copy-Item -LiteralPath $payload -Destination (Join-Path $full "extra-source") -Recurse -Force;[IO.File]::WriteAllBytes((Join-Path $portable "payload\extra.bin"),[Text.Encoding]::UTF8.GetBytes("extra"));$extra=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $verifyScript -RepoRoot $RepoRoot -SealPath (Join-Path $portable "receipts\backup-set.seal.v1.json") -WorkspaceRoot $portable;if($LASTEXITCODE-ne0){Die "EXTRA_VERIFY_EXIT" ([string]$LASTEXITCODE)};$er=LDREC-ReadReceiptFromOutput $extra "ld.backup.set.verify.receipt.v1" $schemaDir;Require (-not[bool]$er.ok) "EXTRA_NOT_BLOCKED" "";Require ([bool](@($er.blockers|Where-Object{([string]$_)-match"EXTRA_PAYLOAD_FILE"}).Count -gt 0)) "EXTRA_REASON" ""
Write-Output "PASS: deterministic seal is created through a partial file and verified independently";Write-Output "PASS: copied workspace verifies portably from its relative payload manifest";Write-Output "PASS: tampered and extra payload bytes fail closed";Write-Output "SELFTEST_LD_BACKUP_SET_SEAL_OK"
