param([Parameter(Mandatory=$true)][string]$RepoRoot,[Parameter(Mandatory=$true)][string]$DestinationRoot,[ValidateSet("plan","quarantine")][string]$Action="plan",[int]$KeepLast=3,[int]$OlderThanDays=30,[string]$WorkspaceManifestPath="",[string]$ExpectedManifestSha256="",[switch]$Execute)
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $PSScriptRoot "_lib_ld_receipts_v1.ps1");. (Join-Path $PSScriptRoot "_lib_ld_destination_profile_v1.ps1");. (Join-Path $PSScriptRoot "_lib_ld_backend_state_v1.ps1");$DestinationRoot=LDBS-FullPath $DestinationRoot;$profile=LDBS-Profile $DestinationRoot $RepoRoot;$rows=@();$blockers=@();$writes=$false;$status="planned";$quarantinePath=""
if($KeepLast-lt1){$blockers+=,"KEEP_LAST_INVALID"};if($OlderThanDays-lt0){$blockers+=,"OLDER_THAN_DAYS_INVALID"}
if($Action-eq"plan"-and$blockers.Count-eq0){
 $manifests=@(Get-ChildItem -LiteralPath (Join-Path $DestinationRoot "content") -Recurse -File -Filter workspace.v1.json -ErrorAction SilentlyContinue);$groups=$manifests|Group-Object {try{[string](LDBS-ReadJson $_.FullName).device_identity_sha256}catch{"invalid"}};foreach($g in @($groups|Sort-Object Name)){ $items=@();foreach($f in @($g.Group)){$w=LDBS-Workspace $f.FullName $RepoRoot;$items+=,[ordered]@{file=$f;manifest=$w.value;sha=$w.sha256;created=[DateTimeOffset]::Parse([string]$w.value.created_utc)}};$rank=0;foreach($i in @($items|Sort-Object created -Descending)){$rank++;$age=[int][Math]::Floor(([DateTimeOffset]::UtcNow-$i.created).TotalDays);$candidate=($rank-gt$KeepLast-and$age-ge$OlderThanDays);$rows+=,[ordered]@{backup_id=[string]$i.manifest.backup_id;device_name=[string]$i.manifest.device_name;workspace_root=[string]$i.manifest.workspace_root;workspace_manifest_path=$i.file.FullName;workspace_manifest_sha256=[string]$i.sha;age_days=$age;newest_rank=$rank;decision=$(if($candidate){"quarantine_candidate"}else{"keep"})}}}
}elseif($Action-eq"quarantine"-and$blockers.Count-eq0){
 try{$w=LDBS-Workspace $WorkspaceManifestPath $RepoRoot;if([string]::IsNullOrWhiteSpace($ExpectedManifestSha256)){throw "EXPECTED_MANIFEST_SHA256_REQUIRED"};if([string]$w.sha256-cne$ExpectedManifestSha256.ToLowerInvariant()){throw "WORKSPACE_MANIFEST_HASH_MISMATCH"};$root=LDBS-FullPath ([string]$w.value.workspace_root);if(-not(LDBS-IsSameOrNested $root (Join-Path $DestinationRoot "content"))){throw "WORKSPACE_OUTSIDE_MANAGED_CONTENT"};$quarantineBase=Join-Path $DestinationRoot "quarantine\cleared-copies";$quarantinePath=Join-Path $quarantineBase ((LDDST-SafeSegment ([string]$w.value.device_name) "device")+"--"+[string]$w.value.backup_id);if(Test-Path -LiteralPath $quarantinePath){throw "QUARANTINE_COLLISION"};$rows+=,[ordered]@{backup_id=[string]$w.value.backup_id;device_name=[string]$w.value.device_name;workspace_root=$root;workspace_manifest_path=$w.path;workspace_manifest_sha256=$w.sha256;age_days=0;newest_rank=0;decision="quarantine_selected"};if($Execute){LDREC-EnsureDir $quarantineBase;Move-Item -LiteralPath $root -Destination $quarantinePath;$moved=Join-Path $quarantinePath "workspace.v1.json";if((LDREC-HexSha256File $moved)-cne$ExpectedManifestSha256.ToLowerInvariant()){throw "QUARANTINED_MANIFEST_HASH_MISMATCH"};$writes=$true;$status="quarantined_verified"}else{$status="dry_run_ready"}}catch{$blockers+=,[string]$_.Exception.Message;$status="blocked"}
}
$ok=($blockers.Count-eq0);$receipt=[ordered]@{schema="ld.backup.retention.receipt.v1";event_type="ld.backup.retention.receipt.v1";ok=[bool]$ok;availability=$(if($ok){"available"}else{"blocked"});repo_root=$RepoRoot;destination_root=$DestinationRoot;destination_profile_id=[string]$profile.value.profile_id;action=$Action;execute_requested=[bool]$Execute;destructive=$false;permanent_delete=$false;writes_destination=[bool]$writes;keep_last=$KeepLast;older_than_days=$OlderThanDays;row_count=[int]$rows.Count;execution_status=$status;quarantine_path=$quarantinePath;rows=@($rows);blockers=@($blockers);created_utc=[DateTime]::UtcNow.ToString("o")};$json=$receipt|ConvertTo-Json -Depth 50 -Compress;Write-Output $json;if($ok){Write-Output "LD_BACKUP_RETENTION_OK"}else{Write-Output "LD_BACKUP_RETENTION_BLOCKED"}
