param([Parameter(Mandatory=$true)][string]$RepoRoot)

Set-StrictMode -Version Latest
$ErrorActionPreference="Stop"
function Die([string]$Code,[string]$Detail){throw($Code+":"+$Detail)}
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Force -Path $Path|Out-Null}}
function WriteLf([string]$Path,[string]$Text){$dir=Split-Path -Parent $Path;EnsureDir $dir;$t=($Text-replace"`r`n","`n")-replace"`r","`n";if(-not$t.EndsWith("`n")){$t+="`n"};[IO.File]::WriteAllText($Path,$t,[Text.UTF8Encoding]::new($false))}
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $RepoRoot "scripts\storage\_lib_ld_receipts_v1.ps1")
$guard=Join-Path $RepoRoot "scripts\storage\ld_blocked_copy_executor_guard_v1.ps1";if(-not(Test-Path -LiteralPath $guard -PathType Leaf)){Die "GUARD_SCRIPT_MISSING" $guard}
$out=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $guard -RepoRoot $RepoRoot -DestinationPath $RepoRoot -MaxFiles 20 -MaxBytes 1048576 -MaxFilesPerSource 20 -MaxDirsPerSource 10 -MaxSamplesPerSource 5
if($LASTEXITCODE-ne0){Die "GUARD_EXIT_NONZERO" ([string]$LASTEXITCODE)}
$guardReceipt=LDREC-ReadReceiptFromOutput $out "ld.device.blocked_copy_executor_guard.receipt.v1" (Join-Path $RepoRoot "schemas")
$guardPathLine=@($out|Where-Object{([string]$_)-match"^DEVICE_BLOCKED_COPY_EXECUTOR_GUARD_PATH:"})|Select-Object -First 1;if($null-eq$guardPathLine){Die "GUARD_RECEIPT_PATH_MISSING" ""};$guardReceiptPath=([string]$guardPathLine).Substring(([string]$guardPathLine).IndexOf(":")+1).Trim();if(-not(Test-Path -LiteralPath $guardReceiptPath -PathType Leaf)){Die "GUARD_RECEIPT_FILE_MISSING" $guardReceiptPath};$guardReceiptHash=LDREC-HexSha256File $guardReceiptPath
$rows=@([ordered]@{row_id="negative-repo-root-contract";source_root=$RepoRoot;destination_root=$RepoRoot;disposition="WOULD_NOT_EXECUTE";performs_copy=$false;writes_destination=$false;reason="guarded contract rejects repository-root destination and dry-run execution"})
$wouldExecuteCount=0;$wouldNotExecuteCount=1;$ok=([bool]$guardReceipt.ok -and -not[bool]$guardReceipt.would_invoke_future_executor -and -not[bool]$guardReceipt.performs_copy -and -not[bool]$guardReceipt.writes_destination)
$receipt=[ordered]@{schema="ld.device.bounded_copy_executor_dry_run_harness.receipt.v1";event_type="ld.device.bounded_copy_executor_dry_run_harness.receipt.v1";ok=[bool]$ok;repo_root=$RepoRoot;mode="bounded_copy_executor_dry_run_harness";destructive=$false;write_test=$false;performs_copy=$false;writes_destination=$false;hashes_file_contents=$false;guard_schema="ld.device.blocked_copy_executor_guard.receipt.v1";guard_receipt_path=$guardReceiptPath;guard_would_invoke_future_executor=[bool]$guardReceipt.would_invoke_future_executor;guard_receipt_sha256=$guardReceiptHash;candidate_count=1;would_execute_count=$wouldExecuteCount;would_not_execute_count=$wouldNotExecuteCount;rows=$rows;blockers=@();created_utc=[DateTime]::UtcNow.ToString("o")}
$outDir=Join-Path $RepoRoot "proofs\receipts\device_bounded_copy_executor_dry_run_harness";EnsureDir $outDir;$outPath=Join-Path $outDir ("bounded_copy_executor_dry_run_harness_"+[DateTime]::UtcNow.ToString("yyyyMMdd_HHmmss_fff")+".json");$json=$receipt|ConvertTo-Json -Depth 50 -Compress;WriteLf $outPath $json;Write-Output ("DEVICE_BOUNDED_COPY_EXECUTOR_DRY_RUN_HARNESS_PATH: "+$outPath);Write-Output ("DEVICE_BOUNDED_COPY_EXECUTOR_DRY_RUN_HARNESS_WOULD_EXECUTE: "+$wouldExecuteCount);Write-Output $json;if($ok){Write-Output "LD_DEVICE_BOUNDED_COPY_EXECUTOR_DRY_RUN_HARNESS_OK"}else{Write-Output "LD_DEVICE_BOUNDED_COPY_EXECUTOR_DRY_RUN_HARNESS_BLOCKED"}
