param([Parameter(Mandatory=$true)][string]$RepoRoot,[Parameter(Mandatory=$true)][string]$SealPath,[Parameter(Mandatory=$true)][string]$WorkspaceRoot)
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Force -Path $Path|Out-Null}}
function Write-Lf([string]$Path,[string]$Text){EnsureDir(Split-Path -Parent $Path);$t=($Text-replace"`r`n","`n")-replace"`r","`n";if(-not$t.EndsWith("`n")){$t+="`n"};[IO.File]::WriteAllText($Path,$t,[Text.UTF8Encoding]::new($false))}
function Add-Unique([object[]]$Items,[string]$Value){$o=@($Items);if(-not($o-contains$Value)){$o+=$Value};return @($o)}
function Rel([string]$Root,[string]$Path){$prefix=[IO.Path]::GetFullPath($Root).TrimEnd("\")+"\";$full=[IO.Path]::GetFullPath($Path);if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){return ""};return $full.Substring($prefix.Length).Replace("\","/")}
function SafeRel([string]$Path){if([string]::IsNullOrWhiteSpace($Path)-or$Path.StartsWith("/")-or$Path-match"^[A-Za-z]:"-or$Path.Split("/")-contains".."){return $false};return $true}

$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $RepoRoot "scripts\storage\_lib_ld_receipts_v1.ps1");. (Join-Path $RepoRoot "scripts\storage\_lib_ld_backend_state_v1.ps1");$errors=@();$rows=@();$seal=$null;$manifest=$null;$actual=@();$actualBytes=[Int64]0
if(-not(Test-Path -LiteralPath $SealPath -PathType Leaf)){$errors=Add-Unique $errors "SEAL_MISSING" $SealPath}else{$SealPath=(Resolve-Path -LiteralPath $SealPath).Path;try{$seal=LDREC-ConvertFromJson (Get-Content -LiteralPath $SealPath -Raw);$schema=LDREC-ConvertFromJson (Get-Content -LiteralPath (Join-Path $RepoRoot "schemas\ld.backup.set.seal.v1.json") -Raw);LDREC-AssertReceiptAgainstSchema -Receipt $seal -Schema $schema -ExpectedSchema "ld.backup.set.seal.v1";$noHash=[ordered]@{schema="ld.backup.set.content.v1";workspace_manifest_sha256=[string]$seal.workspace_manifest_sha256;payload_root_relative=[string]$seal.payload_root_relative;file_count=[int]$seal.file_count;total_bytes=[Int64]$seal.total_bytes;files=@($seal.files|ForEach-Object{LDBS-Plain $_})};if((LDREC-HexSha256TextLf (LDREC-ToCanonJson $noHash))-cne[string]$seal.seal_sha256){$errors=Add-Unique $errors "SEAL_HASH_MISMATCH"}}catch{$errors=Add-Unique $errors ("SEAL_INVALID:"+[string]$_.Exception.Message)}}
$WorkspaceRoot=[IO.Path]::GetFullPath($WorkspaceRoot).TrimEnd("\");$manifestPath=Join-Path $WorkspaceRoot "workspace.v1.json";$payloadRoot=Join-Path $WorkspaceRoot "payload";if(-not(Test-Path -LiteralPath $manifestPath -PathType Leaf)){$errors=Add-Unique $errors "WORKSPACE_MANIFEST_MISSING"}else{try{$manifest=LDREC-ConvertFromJson (Get-Content -LiteralPath $manifestPath -Raw);$ms=LDREC-ConvertFromJson (Get-Content -LiteralPath (Join-Path $RepoRoot "schemas\ld.backup.workspace_manifest.v1.json") -Raw);LDREC-AssertReceiptAgainstSchema -Receipt $manifest -Schema $ms -ExpectedSchema "ld.backup.workspace_manifest.v1"}catch{$errors=Add-Unique $errors ("WORKSPACE_MANIFEST_INVALID:"+[string]$_.Exception.Message)}}
if($null-ne$seal-and$null-ne$manifest){if((LDREC-HexSha256File $manifestPath)-cne[string]$seal.workspace_manifest_sha256){$errors=Add-Unique $errors "WORKSPACE_MANIFEST_HASH_MISMATCH"}}
if(-not(Test-Path -LiteralPath $payloadRoot -PathType Container)){$errors=Add-Unique $errors "PAYLOAD_ROOT_MISSING"}else{foreach($f in @(Get-ChildItem -LiteralPath $payloadRoot -File -Recurse -Force -ErrorAction SilentlyContinue|Sort-Object FullName)){if(($f.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){$errors=Add-Unique $errors "PAYLOAD_REPARSE_FILE";continue};$r=Rel $payloadRoot $f.FullName;$h=LDREC-HexSha256File $f.FullName;$actual+=,[ordered]@{relative_path=$r;size_bytes=[Int64]$f.Length;sha256=$h};$actualBytes+=[Int64]$f.Length}}
if($null-ne$seal){foreach($expected in @($seal.files)){$r=[string]$expected.relative_path;$match=@($actual|Where-Object{([string]$_.relative_path)-ceq$r});$rowErrors=@();if(-not(SafeRel $r)){$rowErrors=Add-Unique $rowErrors "SEALED_RELATIVE_PATH_UNSAFE"}elseif($match.Count-ne1){$rowErrors=Add-Unique $rowErrors "SEALED_FILE_MISSING"}else{if([Int64]$match[0].size_bytes-ne[Int64]$expected.size_bytes){$rowErrors=Add-Unique $rowErrors "SIZE_MISMATCH"};if(([string]$match[0].sha256)-cne([string]$expected.sha256)){$rowErrors=Add-Unique $rowErrors "HASH_MISMATCH"}};$rows+=,[ordered]@{relative_path=$r;verify_ok=(@($rowErrors).Count-eq0);errors=@($rowErrors)};foreach($e in @($rowErrors)){$errors=Add-Unique $errors ($r+":"+$e)}};foreach($extra in @($actual)){ $found=$false;foreach($expected in @($seal.files)){if(([string]$expected.relative_path)-ceq([string]$extra.relative_path)){$found=$true;break}};if(-not$found){$errors=Add-Unique $errors (([string]$extra.relative_path)+":EXTRA_PAYLOAD_FILE")}};if([int]$actual.Count-ne[int]$seal.file_count){$errors=Add-Unique $errors "FILE_COUNT_MISMATCH"};if($actualBytes-ne[Int64]$seal.total_bytes){$errors=Add-Unique $errors "TOTAL_BYTES_MISMATCH"}}
$ok=(@($errors).Count-eq0);$receipt=[ordered]@{schema="ld.backup.set.verify.receipt.v1";event_type="ld.backup.set.verify.receipt.v1";ok=[bool]$ok;availability=$(if($ok){"available"}else{"blocked"});repo_root=$RepoRoot;mode="backup_set_verify";destructive=$false;writes_source=$false;performs_copy=$false;writes_destination=$false;hashes_file_contents=$true;consumes_seal_schema="ld.backup.set.seal.v1";seal_path=$SealPath;seal_sha256=$(if($null-ne$seal){[string]$seal.seal_sha256}else{""});workspace_root=$WorkspaceRoot;workspace_manifest_sha256=$(if($null-ne$manifest){LDREC-HexSha256File $manifestPath}else{""});file_count=[int]$actual.Count;total_bytes=[Int64]$actualBytes;verified_file_count=[int](@($rows|Where-Object{$_.verify_ok}).Count);verification_status=$(if($ok){"verified"}else{"blocked"});rows=@($rows);blockers=@($errors);created_utc=[DateTime]::UtcNow.ToString("o")};$outDir=Join-Path $RepoRoot "proofs\receipts\backup_set_verify";EnsureDir $outDir;$outPath=Join-Path $outDir ("backup_set_verify_"+[DateTime]::UtcNow.ToString("yyyyMMdd_HHmmss_fff")+".json");Write-Lf $outPath ($receipt|ConvertTo-Json -Depth 100 -Compress);Write-Output("BACKUP_SET_VERIFY_PATH: "+$outPath);Write-Output($receipt|ConvertTo-Json -Depth 100 -Compress);if($ok){Write-Output "LD_BACKUP_SET_VERIFY_OK"}else{Write-Output "LD_BACKUP_SET_VERIFY_BLOCKED"}
