param([Parameter(Mandatory=$true)][string]$RepoRoot,[Parameter(Mandatory=$true)][string]$WorkspaceManifestPath,[switch]$Execute)
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
function Die([string]$Code,[string]$Detail){throw($Code+":"+$Detail)}
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Force -Path $Path|Out-Null}}
function Write-Lf([string]$Path,[string]$Text){EnsureDir(Split-Path -Parent $Path);$t=($Text-replace"`r`n","`n")-replace"`r","`n";if(-not$t.EndsWith("`n")){$t+="`n"};[IO.File]::WriteAllText($Path,$t,[Text.UTF8Encoding]::new($false))}
function SafeStr([object]$Value){if($null-eq$Value){return ""};return [string]$Value}
function Add-Unique([object[]]$Items,[string]$Value){$o=@($Items);if(-not($o-contains$Value)){$o+=$Value};return @($o)}
function RelPath([string]$Root,[string]$Path){$prefix=[IO.Path]::GetFullPath($Root).TrimEnd("\")+"\";$full=[IO.Path]::GetFullPath($Path);if(-not$full.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)){Die "PAYLOAD_PATH_ESCAPE" $Path};return $full.Substring($prefix.Length).Replace("\","/")}
function IsReparse([string]$Path){try{$i=Get-Item -LiteralPath $Path -Force -ErrorAction Stop;return (($i.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0)}catch{return $true}}

$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $RepoRoot "scripts\storage\_lib_ld_receipts_v1.ps1");. (Join-Path $RepoRoot "scripts\storage\_lib_ld_backend_state_v1.ps1")
$blockers=@();$status="blocked";$writes=$false;$sealPath="";$sealSha="";$fileRows=@();$totalBytes=[Int64]0;$workspace=$null
try{$workspace=LDBS-Workspace $WorkspaceManifestPath $RepoRoot}catch{$blockers=Add-Unique $blockers ("WORKSPACE_MANIFEST_INVALID:"+[string]$_.Exception.Message)}
if($null-ne$workspace){
  $manifest=[object]$workspace.value;$workspaceRoot=LDBS-FullPath ([string]$manifest.workspace_root);$payloadRoot=LDBS-FullPath ([string]$manifest.payload_path);$receiptsRoot=LDBS-FullPath ([string]$manifest.receipts_path);$sealPath=Join-Path $receiptsRoot "backup-set.seal.v1.json"
  if(-not(Test-Path -LiteralPath $payloadRoot -PathType Container)){$blockers=Add-Unique $blockers "PAYLOAD_ROOT_MISSING"}
  if(-not(LDBS-IsSameOrNested $payloadRoot $workspaceRoot)){$blockers=Add-Unique $blockers "PAYLOAD_ROOT_ESCAPE"}
  if(IsReparse $workspaceRoot){$blockers=Add-Unique $blockers "WORKSPACE_ROOT_REPARSE_POINT_FORBIDDEN"}
  if((Test-Path -LiteralPath $payloadRoot -PathType Container) -and (IsReparse $payloadRoot)){$blockers=Add-Unique $blockers "PAYLOAD_ROOT_REPARSE_POINT_FORBIDDEN"}
  if(Test-Path -LiteralPath $payloadRoot -PathType Container){
    foreach($file in @(Get-ChildItem -LiteralPath $payloadRoot -File -Recurse -Force -ErrorAction Stop|Sort-Object FullName)){
      if(($file.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){$blockers=Add-Unique $blockers "PAYLOAD_REPARSE_FILE_FORBIDDEN";continue}
      $rel=RelPath $payloadRoot $file.FullName;if($rel -match "(^|/)\.legacy-doctor\.partial$"){$blockers=Add-Unique $blockers "PARTIAL_PAYLOAD_FILE_PRESENT";continue}
      $size=[Int64]$file.Length;$hash=LDREC-HexSha256File $file.FullName;$fileRows+=,[ordered]@{relative_path=$rel;size_bytes=$size;sha256=$hash};$totalBytes+=$size
    }
  }
}
$canonical=[ordered]@{schema="ld.backup.set.content.v1";workspace_manifest_sha256=$(if($null-ne$workspace){[string]$workspace.sha256}else{""});payload_root_relative="payload";file_count=[int]$fileRows.Count;total_bytes=[Int64]$totalBytes;files=@($fileRows)}
$sealSha=LDREC-HexSha256TextLf (LDREC-ToCanonJson $canonical)
$seal=[ordered]@{schema="ld.backup.set.seal.v1";event_type="ld.backup.set.seal.v1";workspace_manifest_sha256=$canonical.workspace_manifest_sha256;payload_root_relative="payload";file_count=$canonical.file_count;total_bytes=$canonical.total_bytes;files=@($fileRows);seal_sha256=$sealSha}
if(@($blockers).Count-eq0){if(Test-Path -LiteralPath $sealPath -PathType Leaf){try{$existing=LDREC-ConvertFromJson (Get-Content -LiteralPath $sealPath -Raw);$schema=LDREC-ConvertFromJson (Get-Content -LiteralPath (Join-Path $RepoRoot "schemas\ld.backup.set.seal.v1.json") -Raw);LDREC-AssertReceiptAgainstSchema -Receipt $existing -Schema $schema -ExpectedSchema "ld.backup.set.seal.v1";$existingNoHash=[ordered]@{schema="ld.backup.set.content.v1";workspace_manifest_sha256=[string]$existing.workspace_manifest_sha256;payload_root_relative=[string]$existing.payload_root_relative;file_count=[int]$existing.file_count;total_bytes=[Int64]$existing.total_bytes;files=@($existing.files|ForEach-Object{LDBS-Plain $_})};if((LDREC-HexSha256TextLf (LDREC-ToCanonJson $existingNoHash))-cne[string]$existing.seal_sha256){throw "EXISTING_SEAL_HASH_INVALID"};if([string]$existing.seal_sha256-cne$sealSha){throw "SEAL_COLLISION"};$status="already_sealed"}catch{$blockers=Add-Unique $blockers ([string]$_.Exception.Message)}}elseif(-not$Execute.IsPresent){$status="dry_run_ready"}else{try{$temp=$sealPath+".partial";if(Test-Path -LiteralPath $temp){throw "STALE_SEAL_PARTIAL"};Write-Lf $temp (LDREC-ToCanonJson $seal);$check=LDREC-ConvertFromJson (Get-Content -LiteralPath $temp -Raw);$schema=LDREC-ConvertFromJson (Get-Content -LiteralPath (Join-Path $RepoRoot "schemas\ld.backup.set.seal.v1.json") -Raw);LDREC-AssertReceiptAgainstSchema -Receipt $check -Schema $schema -ExpectedSchema "ld.backup.set.seal.v1";[IO.File]::Move($temp,$sealPath);$writes=$true;$status="sealed_verified"}catch{$blockers=Add-Unique $blockers ("SEAL_WRITE_FAILED:"+[string]$_.Exception.Message);if(Test-Path -LiteralPath ($sealPath+".partial")){Remove-Item -LiteralPath ($sealPath+".partial") -Force -ErrorAction SilentlyContinue}}}}
$ok=(@($blockers).Count-eq0);$availability=$(if($ok){"available"}else{"blocked"});if(-not$ok){$status="blocked"}
$receipt=[ordered]@{schema="ld.backup.set.seal.receipt.v1";event_type="ld.backup.set.seal.receipt.v1";ok=[bool]$ok;availability=$availability;repo_root=$RepoRoot;mode="backup_set_seal";destructive=$false;writes_source=$false;execute_requested=[bool]$Execute.IsPresent;writes_workspace=[bool]$writes;workspace_manifest_path=$(if($null-ne$workspace){[string]$workspace.path}else{""});workspace_manifest_sha256=$canonical.workspace_manifest_sha256;seal_path=$sealPath;seal_sha256=$sealSha;file_count=[int]$fileRows.Count;total_bytes=[Int64]$totalBytes;verification_status=$status;blockers=@($blockers);created_utc=[DateTime]::UtcNow.ToString("o")};$outDir=Join-Path $RepoRoot "proofs\receipts\backup_set_seal";EnsureDir $outDir;$outPath=Join-Path $outDir ("backup_set_seal_"+[DateTime]::UtcNow.ToString("yyyyMMdd_HHmmss_fff")+".json");Write-Lf $outPath ($receipt|ConvertTo-Json -Depth 100 -Compress);Write-Output("BACKUP_SET_SEAL_PATH: "+$outPath);Write-Output($receipt|ConvertTo-Json -Depth 100 -Compress);if($ok){Write-Output "LD_BACKUP_SET_SEAL_OK"}else{Write-Output "LD_BACKUP_SET_SEAL_BLOCKED"}
