param([Parameter(Mandatory=$true)][string]$RepoRoot,[Parameter(Mandatory=$true)][string]$StateRoot,[ValidateSet("register","list","verify")][string]$Action="list",[string]$DestinationRoot="",[switch]$Execute)
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $PSScriptRoot "_lib_ld_receipts_v1.ps1");. (Join-Path $PSScriptRoot "_lib_ld_destination_profile_v1.ps1");. (Join-Path $PSScriptRoot "_lib_ld_backend_state_v1.ps1")
$StateRoot=LDBS-FullPath $StateRoot;$rows=@();$blockers=@();$writes=$false;$status="listed";$layout=LDBS-Layout $StateRoot
if($Action-eq"register"){
  if([string]::IsNullOrWhiteSpace($DestinationRoot)){$blockers+=,"DESTINATION_ROOT_REQUIRED"}else{try{$p=LDBS-Profile $DestinationRoot $RepoRoot;$entry=[ordered]@{schema="ld.backend.destination_registration.v1";event_type="ld.backend.destination_registration.v1";profile_id=[string]$p.value.profile_id;profile_sha256=[string]$p.sha256;profile_path=[string]$p.path;destination_root=[string]$p.value.root_path;label=[string]$p.value.label;registered_utc=[DateTime]::UtcNow.ToString("o")};$entryPath=Join-Path $layout.destinations (([string]$p.value.profile_id)+".json");if($Execute){$layout=LDBS-EnsureLayout $StateRoot;if(Test-Path -LiteralPath $entryPath){$old=LDBS-ReadJson $entryPath;if([string]$old.profile_sha256-cne[string]$p.sha256){throw "REGISTERED_PROFILE_HASH_MISMATCH"};$status="already_registered"}else{$writes=LDBS-WriteImmutableJson $entryPath $entry;$status="registered"}}else{$status="dry_run_ready"};$rows+=,[ordered]@{profile_id=[string]$p.value.profile_id;label=[string]$p.value.label;destination_root=[string]$p.value.root_path;profile_sha256=[string]$p.sha256;available=$true;registration_path=$entryPath}}catch{$blockers+=,[string]$_.Exception.Message;$status="blocked"}}
}else{
  if(Test-Path -LiteralPath $layout.destinations -PathType Container){foreach($file in @(Get-ChildItem -LiteralPath $layout.destinations -File -Filter *.json|Sort-Object Name)){try{$e=LDBS-ReadJson $file.FullName;LDBS-AssertSchema $e "ld.backend.destination_registration.v1" $RepoRoot;$p=LDBS-Profile ([string]$e.destination_root) $RepoRoot;$valid=([string]$p.sha256-ceq[string]$e.profile_sha256);$rows+=,[ordered]@{profile_id=[string]$e.profile_id;label=[string]$e.label;destination_root=[string]$e.destination_root;profile_sha256=[string]$e.profile_sha256;available=[bool]$valid;registration_path=$file.FullName};if(-not$valid){$blockers+=,"PROFILE_HASH_MISMATCH"}}catch{$rows+=,[ordered]@{profile_id=$file.BaseName;label="";destination_root="";profile_sha256="";available=$false;registration_path=$file.FullName};$blockers+=,[string]$_.Exception.Message}}};$status=$(if($Action-eq"verify"-and$blockers.Count-gt 0){"blocked"}elseif($Action-eq"verify"){"verified"}else{"listed"})
}
$ok=($blockers.Count-eq0);$receipt=[ordered]@{schema="ld.backend.destination_registry.receipt.v1";event_type="ld.backend.destination_registry.receipt.v1";ok=[bool]$ok;availability=$(if($ok){"available"}else{"blocked"});repo_root=$RepoRoot;state_root=$StateRoot;action=$Action;execute_requested=[bool]$Execute;writes_state=[bool]$writes;entry_count=[int]$rows.Count;execution_status=$status;rows=@($rows);blockers=@($blockers);created_utc=[DateTime]::UtcNow.ToString("o")};$json=$receipt|ConvertTo-Json -Depth 30 -Compress;Write-Output $json;if($ok){Write-Output "LD_BACKEND_DESTINATION_REGISTRY_OK"}else{Write-Output "LD_BACKEND_DESTINATION_REGISTRY_BLOCKED"}
