param(
  [Parameter(Mandatory=$true)][string]$RepoRoot,
  [Parameter(Mandatory=$true)][string]$DestinationRoot,
  [Parameter(Mandatory=$true)][ValidateSet("file_backup","disk_image","optical_image","device_export")][string]$BackupMode,
  [Parameter(Mandatory=$true)][string]$DeviceName,
  [Parameter(Mandatory=$true)][string]$DeviceIdentitySha256,
  [string]$BackupId="",
  [switch]$Execute,
  [switch]$OwnedTestFixture
)

Set-StrictMode -Version Latest
$ErrorActionPreference="Stop"
function Add-Unique([object[]]$Items,[string]$Value){$r=@($Items);if(-not($r-contains$Value)){$r+=$Value};return @($r)}
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Path $Path -ErrorAction Stop|Out-Null}}
function Write-Lf([string]$Path,[string]$Text){$t=($Text-replace"`r`n","`n")-replace"`r","`n";if(-not$t.EndsWith("`n")){$t+="`n"};[IO.File]::WriteAllText($Path,$t,[Text.UTF8Encoding]::new($false))}

$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path
. (Join-Path $PSScriptRoot "_lib_ld_receipts_v1.ps1")
. (Join-Path $PSScriptRoot "_lib_ld_destination_profile_v1.ps1")
$DestinationRoot=LDDST-FullPath $DestinationRoot;$profilePath=LDDST-ProfilePath $DestinationRoot
$blockers=@();$profile=$null;$profileHash="";$existingValid=$false;$writesDestination=$false;$rollbackPerformed=$false;$rollbackOk=$true
if($DeviceIdentitySha256-notmatch"^[a-fA-F0-9]{64}$"){$blockers=Add-Unique $blockers "DEVICE_IDENTITY_SHA256_INVALID"}else{$DeviceIdentitySha256=$DeviceIdentitySha256.ToLowerInvariant()}
if([string]::IsNullOrWhiteSpace($DeviceName)-or$DeviceName.Length-gt 120){$blockers=Add-Unique $blockers "DEVICE_NAME_INVALID"}
if([string]::IsNullOrWhiteSpace($BackupId)){$BackupId=[DateTime]::UtcNow.ToString("yyyyMMdd-HHmmss-fffZ")}
if($BackupId-notmatch"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$"){$blockers=Add-Unique $blockers "BACKUP_ID_INVALID"}
$repoProofs=Join-Path $RepoRoot "proofs\selftest";if(LDDST-IsSameOrNested -Candidate $DestinationRoot -Root $RepoRoot){if(-not($OwnedTestFixture.IsPresent-and(LDDST-IsSameOrNested -Candidate $DestinationRoot -Root $repoProofs))){$blockers=Add-Unique $blockers "REPOSITORY_DESTINATION_FORBIDDEN"}}
if(-not(Test-Path -LiteralPath $profilePath -PathType Leaf)){$blockers=Add-Unique $blockers "DESTINATION_PROFILE_MISSING"}else{
  try{$schema=LDREC-ConvertFromJson (Get-Content -Raw -LiteralPath (Join-Path $RepoRoot "schemas\ld.backup.destination_profile.v1.json"));$profile=LDREC-ConvertFromJson (Get-Content -Raw -LiteralPath $profilePath);LDREC-AssertReceiptAgainstSchema -Receipt $profile -Schema $schema -ExpectedSchema "ld.backup.destination_profile.v1";$profileHash=LDREC-HexSha256File $profilePath;if(-not(LDDST-IsSameOrNested -Candidate ([string]$profile.root_path) -Root $DestinationRoot)-or-not(LDDST-IsSameOrNested -Candidate $DestinationRoot -Root ([string]$profile.root_path))){$blockers=Add-Unique $blockers "PROFILE_ROOT_MISMATCH"}}catch{$blockers=Add-Unique $blockers ("DESTINATION_PROFILE_INVALID:"+[string]$_.Exception.Message)}
}
$basePath="";if($null-ne$profile){try{$basePath=LDDST-ModeFolder -Profile $profile -Mode $BackupMode}catch{$blockers=Add-Unique $blockers ([string]$_.Exception.Message)}}
$deviceSegment=(LDDST-SafeSegment $DeviceName "device")+"--"+$(if($DeviceIdentitySha256.Length-ge 12){$DeviceIdentitySha256.Substring(0,12)}else{"invalid"})
$workspaceRoot=$(if($basePath){Join-Path (Join-Path $basePath $deviceSegment) $BackupId}else{""});$payloadPath=$(if($workspaceRoot){Join-Path $workspaceRoot "payload"}else{""});$metadataPath=$(if($workspaceRoot){Join-Path $workspaceRoot "metadata"}else{""});$receiptsPath=$(if($workspaceRoot){Join-Path $workspaceRoot "receipts"}else{""});$logsPath=$(if($workspaceRoot){Join-Path $workspaceRoot "logs"}else{""});$manifestPath=$(if($workspaceRoot){Join-Path $workspaceRoot "workspace.v1.json"}else{""});$manifestHash=""
if($workspaceRoot-and-not(LDDST-IsSameOrNested -Candidate $workspaceRoot -Root $DestinationRoot)){$blockers=Add-Unique $blockers "WORKSPACE_PATH_ESCAPE"}
if($workspaceRoot-and(Test-Path -LiteralPath $workspaceRoot -PathType Container)){
  if(Test-Path -LiteralPath $manifestPath -PathType Leaf){try{$schema=LDREC-ConvertFromJson (Get-Content -Raw -LiteralPath (Join-Path $RepoRoot "schemas\ld.backup.workspace_manifest.v1.json"));$existing=LDREC-ConvertFromJson (Get-Content -Raw -LiteralPath $manifestPath);LDREC-AssertReceiptAgainstSchema -Receipt $existing -Schema $schema -ExpectedSchema "ld.backup.workspace_manifest.v1";$manifestHash=LDREC-HexSha256File $manifestPath;if(([string]$existing.destination_profile_id)-cne([string]$profile.profile_id)-or([string]$existing.device_identity_sha256-cne$DeviceIdentitySha256)-or([string]$existing.backup_mode-cne$BackupMode)){$blockers=Add-Unique $blockers "WORKSPACE_MANIFEST_MISMATCH"};foreach($dir in @($payloadPath,$metadataPath,$receiptsPath,$logsPath)){if(-not(Test-Path -LiteralPath $dir -PathType Container)){$blockers=Add-Unique $blockers "WORKSPACE_FOLDER_MISSING"}};$existingValid=(@($blockers).Count-eq 0)}catch{$blockers=Add-Unique $blockers ("WORKSPACE_MANIFEST_INVALID:"+[string]$_.Exception.Message)}}else{$blockers=Add-Unique $blockers "UNMANAGED_WORKSPACE_COLLISION"}
}
$preflightReady=(@($blockers).Count-eq 0);$executionAllowed=($Execute.IsPresent-and$preflightReady-and-not$existingValid);$executionFailed=$false;$createdDirs=@()
if($executionAllowed){$tempManifest=$manifestPath+".partial";try{if(-not(Test-Path -LiteralPath (Split-Path -Parent $workspaceRoot) -PathType Container)){EnsureDir (Split-Path -Parent $workspaceRoot);$createdDirs+=(Split-Path -Parent $workspaceRoot)};EnsureDir $workspaceRoot;$createdDirs+=$workspaceRoot;foreach($dir in @($payloadPath,$metadataPath,$receiptsPath,$logsPath)){EnsureDir $dir;$createdDirs+=$dir};$writesDestination=$true;$createdUtc=[DateTime]::UtcNow.ToString("o");$manifest=[ordered]@{schema="ld.backup.workspace_manifest.v1";event_type="ld.backup.workspace_manifest.v1";destination_profile_id=[string]$profile.profile_id;backup_mode=$BackupMode;backup_id=$BackupId;device_name=$DeviceName;device_identity_sha256=$DeviceIdentitySha256;workspace_root=$workspaceRoot;payload_path=$payloadPath;metadata_path=$metadataPath;receipts_path=$receiptsPath;logs_path=$logsPath;source_writes_allowed=$false;created_utc=$createdUtc};Write-Lf $tempManifest (LDREC-ToCanonJson $manifest);$schema=LDREC-ConvertFromJson (Get-Content -Raw -LiteralPath (Join-Path $RepoRoot "schemas\ld.backup.workspace_manifest.v1.json"));$check=LDREC-ConvertFromJson (Get-Content -Raw -LiteralPath $tempManifest);LDREC-AssertReceiptAgainstSchema -Receipt $check -Schema $schema -ExpectedSchema "ld.backup.workspace_manifest.v1";[IO.File]::Move($tempManifest,$manifestPath);$manifestHash=LDREC-HexSha256File $manifestPath}catch{$executionFailed=$true;$blockers=Add-Unique $blockers ("EXECUTION_FAILED:"+[string]$_.Exception.Message);$rollbackPerformed=$true;if(Test-Path -LiteralPath $tempManifest){Remove-Item -LiteralPath $tempManifest -Force -ErrorAction SilentlyContinue};foreach($dir in @($createdDirs|Sort-Object Length -Descending)){try{if((Test-Path -LiteralPath $dir -PathType Container)-and@(Get-ChildItem -LiteralPath $dir -Force).Count-eq 0){Remove-Item -LiteralPath $dir -Force}}catch{$rollbackOk=$false}}}}
$status="dry_run_blocked";$ok=$false;$availability="blocked";if($existingValid){$status="already_configured";$ok=$true;$availability="available"}elseif(-not$Execute.IsPresent-and$preflightReady){$status="dry_run_ready";$ok=$true;$availability="available"}elseif($executionAllowed-and-not$executionFailed-and(Test-Path -LiteralPath $manifestPath -PathType Leaf)){$status="created_verified";$ok=$true;$availability="available"}elseif($executionFailed-and-not$rollbackOk){$status="execution_failed_rollback_incomplete";$availability="failed"}elseif($executionFailed){$status="execution_failed";$availability="failed"}
$receipt=[ordered]@{schema="ld.backup.workspace.receipt.v1";event_type="ld.backup.workspace.receipt.v1";ok=[bool]$ok;availability=$availability;repo_root=$RepoRoot;mode="backup_workspace_setup";destructive=$false;writes_source=$false;execute_requested=[bool]$Execute.IsPresent;destination_profile_id=$(if($null-ne$profile){[string]$profile.profile_id}else{""});destination_profile_sha256=$profileHash;backup_mode=$BackupMode;backup_id=$BackupId;device_name=$DeviceName;device_identity_sha256=$DeviceIdentitySha256;workspace_root=$workspaceRoot;payload_path=$payloadPath;metadata_path=$metadataPath;receipts_path=$receiptsPath;logs_path=$logsPath;workspace_manifest_path=$manifestPath;workspace_manifest_sha256=$manifestHash;preflight_ready=[bool]$preflightReady;execution_allowed=[bool]$executionAllowed;writes_destination=[bool]$writesDestination;rollback_performed=[bool]$rollbackPerformed;rollback_ok=[bool]$rollbackOk;execution_status=$status;blockers=@($blockers);created_utc=[DateTime]::UtcNow.ToString("o")}
$outDir=Join-Path $RepoRoot "proofs\receipts\backup_workspace";New-Item -ItemType Directory -Force -Path $outDir|Out-Null;$outPath=Join-Path $outDir ("backup_workspace_"+[DateTime]::UtcNow.ToString("yyyyMMdd_HHmmss_fff")+".json");$json=$receipt|ConvertTo-Json -Depth 30 -Compress;Write-Lf $outPath $json
Write-Output ("BACKUP_WORKSPACE_PATH: "+$outPath);Write-Output ("BACKUP_WORKSPACE_STATUS: "+$status);Write-Output $json;if($ok){Write-Output "LD_BACKUP_WORKSPACE_OK"}else{Write-Output "LD_BACKUP_WORKSPACE_BLOCKED"}
