param([Parameter(Mandatory=$true)][string]$RepoRoot)

Set-StrictMode -Version Latest
$ErrorActionPreference="Stop"
function Die([string]$Code,[string]$Detail){throw($Code+":"+$Detail)}
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Force -Path $Path|Out-Null}}
function WriteLf([string]$Path,[string]$Text){$dir=Split-Path -Parent $Path;EnsureDir $dir;$t=($Text-replace"`r`n","`n")-replace"`r","`n";if(-not$t.EndsWith("`n")){$t+="`n"};[IO.File]::WriteAllText($Path,$t,[Text.UTF8Encoding]::new($false))}
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $RepoRoot "scripts\storage\_lib_ld_receipts_v1.ps1")
$fixture=Join-Path $RepoRoot "proofs\selftest\storage03_positive_ready_path";$fixtureRoot=[IO.Path]::GetFullPath($fixture);$allowed=[IO.Path]::GetFullPath((Join-Path $RepoRoot "proofs\selftest")).TrimEnd("\")+"\";if(-not$fixtureRoot.StartsWith($allowed,[StringComparison]::OrdinalIgnoreCase)){Die "FIXTURE_ESCAPE" $fixtureRoot};if(Test-Path -LiteralPath $fixtureRoot){Remove-Item -LiteralPath $fixtureRoot -Recurse -Force};EnsureDir $fixtureRoot;$fixtureScripts=Join-Path $fixtureRoot "scripts\storage";$fixtureSchemas=Join-Path $fixtureRoot "schemas";$destination=Join-Path $fixtureRoot "fixture-destination";EnsureDir $fixtureScripts;EnsureDir $fixtureSchemas;EnsureDir $destination
Copy-Item -LiteralPath (Join-Path $RepoRoot "scripts\storage\ld_blocked_copy_executor_guard_v1.ps1") -Destination (Join-Path $fixtureScripts "ld_blocked_copy_executor_guard_v1.ps1") -Force;Copy-Item -LiteralPath (Join-Path $RepoRoot "scripts\storage\_lib_ld_receipts_v1.ps1") -Destination (Join-Path $fixtureScripts "_lib_ld_receipts_v1.ps1") -Force;Copy-Item -LiteralPath (Join-Path $RepoRoot "schemas\ld.device.backup_run_contract.receipt.v1.json") -Destination (Join-Path $fixtureSchemas "ld.device.backup_run_contract.receipt.v1.json") -Force;Copy-Item -LiteralPath (Join-Path $RepoRoot "schemas\ld.device.blocked_copy_executor_guard.receipt.v1.json") -Destination (Join-Path $fixtureSchemas "ld.device.blocked_copy_executor_guard.receipt.v1.json") -Force
$contract=@'
param([Parameter(Mandatory=$true)][string]$RepoRoot,[string]$DestinationPath="",[int]$MaxFiles=0,[Int64]$MaxBytes=0,[switch]$AllowSystemDisk,[switch]$Execute,[int]$MaxFilesPerSource=20,[int]$MaxDirsPerSource=10,[int]$MaxSamplesPerSource=5)
Set-StrictMode -Version Latest
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path
$receipt=[ordered]@{schema="ld.device.backup_run_contract.receipt.v1";event_type="ld.device.backup_run_contract.receipt.v1";ok=$true;repo_root=$RepoRoot;mode="backup_run_contract";destructive=$false;write_test=$false;performs_copy=$false;writes_destination=$false;hashes_file_contents=$false;execution_allowed_now=$true;would_allow_future_bounded_copy=$true;explicit_destination_required=$true;explicit_destination_present=$true;destination_path=$DestinationPath;repo_root_destination_blocked=$false;max_files=[int]$MaxFiles;max_bytes=[Int64]$MaxBytes;max_files_required=$true;max_bytes_required=$true;allow_system_disk=[bool]$AllowSystemDisk;execute_requested=$true;dry_run_default=$false;preflight_schema="ld.device.backup_execution_preflight.receipt.v1";preflight_ready=$true;preflight_actions=@("READY_FOR_BOUNDED_COPY");preflight_write_probe_ok=$true;preflight_manifest_invalid_row_count=0;preflight_manifest_warning_row_count=0;contract_actions=@("CONTRACT_READY_FOR_FUTURE_BOUNDED_COPY_EXECUTOR");action_counts=[ordered]@{CONTRACT_READY_FOR_FUTURE_BOUNDED_COPY_EXECUTOR=1};reasons=@("fixture contract supplies a controlled non-overlapping destination and verified manifest");created_utc=[DateTime]::UtcNow.ToString("o")}
$json=$receipt|ConvertTo-Json -Depth 30 -Compress;Write-Output $json;Write-Output "LD_DEVICE_BACKUP_RUN_CONTRACT_OK"
'@
WriteLf (Join-Path $fixtureScripts "ld_backup_run_contract_v1.ps1") $contract
$guard=Join-Path $fixtureScripts "ld_blocked_copy_executor_guard_v1.ps1";$out=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $guard -RepoRoot $fixtureRoot -DestinationPath $destination -MaxFiles 5 -MaxBytes 65536 -MaxFilesPerSource 5 -MaxDirsPerSource 5 -MaxSamplesPerSource 2 -Execute;if($LASTEXITCODE-ne0){Die "GUARD_EXIT_NONZERO" ([string]$LASTEXITCODE)}
$guardReceipt=LDREC-ReadReceiptFromOutput $out "ld.device.blocked_copy_executor_guard.receipt.v1" $fixtureSchemas;$pathLine=@($out|Where-Object{([string]$_)-match"^DEVICE_BLOCKED_COPY_EXECUTOR_GUARD_PATH:"})|Select-Object -First 1;if($null-eq$pathLine){Die "GUARD_RECEIPT_PATH_MISSING" ""};$guardPath=([string]$pathLine).Substring(([string]$pathLine).IndexOf(":")+1).Trim();if(-not(Test-Path -LiteralPath $guardPath -PathType Leaf)){Die "GUARD_RECEIPT_MISSING" $guardPath};$guardHash=LDREC-HexSha256File $guardPath
$rows=@([ordered]@{row_id="positive-ready-future-executor";source_root=(Join-Path $fixtureRoot "fixture-source");destination_root=$destination;disposition="WOULD_INVOKE_FUTURE_EXECUTOR";performs_copy=$false;writes_destination=$false;reason="real guard accepted the schema-valid ready contract; this fixture still performs no copy"});$ok=([bool]$guardReceipt.ok -and[bool]$guardReceipt.would_invoke_future_executor -and[bool]$guardReceipt.contract_execution_allowed_now -and[bool]$guardReceipt.contract_preflight_ready -and-not[bool]$guardReceipt.performs_copy-and-not[bool]$guardReceipt.writes_destination)
$receipt=[ordered]@{schema="ld.device.storage03_positive_ready_path_fixture.receipt.v1";event_type="ld.device.storage03_positive_ready_path_fixture.receipt.v1";ok=[bool]$ok;repo_root=$RepoRoot;mode="storage03_positive_ready_path_fixture";destructive=$false;write_test=$false;performs_copy=$false;writes_destination=$false;hashes_file_contents=$false;fixture_contract_schema="ld.device.backup_run_contract.receipt.v1";fixture_contract_execution_allowed_now=[bool]$guardReceipt.contract_execution_allowed_now;fixture_contract_would_allow_future_bounded_copy=[bool]$guardReceipt.contract_would_allow_future_bounded_copy;fixture_preflight_ready=[bool]$guardReceipt.contract_preflight_ready;guard_schema="ld.device.blocked_copy_executor_guard.receipt.v1";guard_receipt_path=$guardPath;guard_receipt_sha256=$guardHash;guard_would_invoke_future_executor=[bool]$guardReceipt.would_invoke_future_executor;candidate_count=1;would_execute_count=1;would_not_execute_count=0;rows=$rows;blockers=@();created_utc=[DateTime]::UtcNow.ToString("o")}
$outDir=Join-Path $RepoRoot "proofs\receipts\device_storage03_positive_ready_path_fixture";EnsureDir $outDir;$outPath=Join-Path $outDir ("storage03_positive_ready_path_fixture_"+[DateTime]::UtcNow.ToString("yyyyMMdd_HHmmss_fff")+".json");$json=$receipt|ConvertTo-Json -Depth 50 -Compress;WriteLf $outPath $json;Write-Output ("DEVICE_STORAGE03_POSITIVE_READY_PATH_FIXTURE_PATH: "+$outPath);Write-Output $json;if($ok){Write-Output "LD_DEVICE_STORAGE03_POSITIVE_READY_PATH_FIXTURE_OK"}else{Write-Output "LD_DEVICE_STORAGE03_POSITIVE_READY_PATH_FIXTURE_BLOCKED"}
