param([Parameter(Mandatory=$true)][string]$RepoRoot)
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
function Die([string]$Code,[string]$Detail){throw($Code+":"+$Detail)}
function Require([bool]$Condition,[string]$Code,[string]$Detail){if(-not$Condition){Die $Code $Detail}}
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Force -Path $Path|Out-Null}}
function Write-Lf([string]$Path,[string]$Text){EnsureDir(Split-Path -Parent $Path);$t=($Text-replace"`r`n","`n")-replace"`r","`n";if(-not$t.EndsWith("`n")){$t+="`n"};[IO.File]::WriteAllText($Path,$t,[Text.UTF8Encoding]::new($false))}
function PathDrive([string]$Path){try{$r=[IO.Path]::GetPathRoot([IO.Path]::GetFullPath($Path));if($r.Length-ge2-and$r.Substring(1,1)-eq":"){return $r.Substring(0,1).ToUpperInvariant()}}catch{};return ""}
function VolumeFs([string]$Drive){if([string]::IsNullOrWhiteSpace($Drive)){return ""};try{foreach($v in @(Get-Volume -DriveLetter $Drive -ErrorAction Stop)){return [string]$v.FileSystem}}catch{};return ""}
function RunReceipt([string]$Script,[string]$Schema,[string[]]$ScriptArgs){$a=@("-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File",$Script);$a+=$ScriptArgs;$out=& powershell.exe @a;if($LASTEXITCODE-ne0){Die "CHILD_EXIT" ($Script+":"+[string]$LASTEXITCODE)};return (LDREC-ReadReceiptFromOutput $out $Schema (Join-Path $RepoRoot "schemas"))}

$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $RepoRoot "scripts\storage\_lib_ld_receipts_v1.ps1");$base=Join-Path $RepoRoot "proofs\selftest\storage03_destination_matrix";$allowed=[IO.Path]::GetFullPath((Join-Path $RepoRoot "proofs\selftest")).TrimEnd("\")+"\";$full=[IO.Path]::GetFullPath($base);Require $full.StartsWith($allowed,[StringComparison]::OrdinalIgnoreCase) "FIXTURE_ESCAPE" $full;if(Test-Path -LiteralPath $full){Remove-Item -LiteralPath $full -Recurse -Force};$source=Join-Path $full "source";$local=Join-Path $full "local-destination";$missing=Join-Path $full "missing-destination";EnsureDir $source;EnsureDir $local;[IO.File]::WriteAllBytes((Join-Path $source "matrix.m4a"),[Text.Encoding]::UTF8.GetBytes("matrix-bytes"))
$backup=Join-Path $RepoRoot "scripts\media\ld_mounted_media_backup_v1.ps1";$probe=Join-Path $RepoRoot "scripts\storage\ld_destination_write_probe_v1.ps1";$drive=PathDrive $local;$fs=VolumeFs $drive;$localProbe=RunReceipt $probe "ld.device.destination_write_probe.receipt.v1" @("-RepoRoot",$RepoRoot,"-DestinationPath",$local);Require ([bool]$localProbe.write_probe_ok) "LOCAL_WRITE_PROBE" "";$localRun=RunReceipt $backup "ld.media.mounted_backup.receipt.v1" @("-RepoRoot",$RepoRoot,"-SourceRoot",$source,"-DestinationRoot",$local,"-MaxFiles","10","-MaxBytes","1048576","-Execute");Require ([bool]$localRun.ok) "LOCAL_COPY" ([string]$localRun.execution_status);Require ([int]$localRun.verified_file_count-eq1) "LOCAL_VERIFY" ""
$sameRun=RunReceipt $backup "ld.media.mounted_backup.receipt.v1" @("-RepoRoot",$RepoRoot,"-SourceRoot",$source,"-DestinationRoot",$source,"-MaxFiles","10","-MaxBytes","1048576","-Execute");Require (-not[bool]$sameRun.ok) "OVERLAP_NOT_BLOCKED" "";Require (@($sameRun.blockers)-contains "SOURCE_DESTINATION_OVERLAP") "OVERLAP_REASON" ""
$repoRun=RunReceipt $backup "ld.media.mounted_backup.receipt.v1" @("-RepoRoot",$RepoRoot,"-SourceRoot",$source,"-DestinationRoot",$RepoRoot,"-MaxFiles","10","-MaxBytes","1048576","-Execute");Require (-not[bool]$repoRun.ok) "REPO_DEST_NOT_BLOCKED" "";Require (@($repoRun.blockers)-contains "REPO_ROOT_DESTINATION_FORBIDDEN") "REPO_DEST_REASON" ""
$missingProbe=RunReceipt $probe "ld.device.destination_write_probe.receipt.v1" @("-RepoRoot",$RepoRoot,"-DestinationPath",$missing);Require (-not[bool]$missingProbe.write_probe_ok) "MISSING_DEST_WRITE" "";Require ([string]$missingProbe.error -eq "DESTINATION_MISSING") "MISSING_DEST_REASON" ([string]$missingProbe.error)
$rows=@([ordered]@{destination_class="local_host_directory";filesystem=$fs;status="verified";operation="write_probe_and_bounded_copy";proofs=@("ld.device.destination_write_probe.receipt.v1","ld.media.mounted_backup.receipt.v1");actions=@("READY_DESTINATION")},[ordered]@{destination_class="same_source_root";filesystem=$fs;status="blocked";operation="bounded_copy";proofs=@("ld.media.mounted_backup.receipt.v1");actions=@("SOURCE_DESTINATION_OVERLAP")},[ordered]@{destination_class="repository_root";filesystem=$fs;status="blocked";operation="bounded_copy";proofs=@("ld.media.mounted_backup.receipt.v1");actions=@("REPO_ROOT_DESTINATION_FORBIDDEN")},[ordered]@{destination_class="missing_local_path";filesystem=$fs;status="blocked";operation="write_probe";proofs=@("ld.device.destination_write_probe.receipt.v1");actions=@("DESTINATION_MISSING")},[ordered]@{destination_class="unc_network_share";filesystem="unknown";status="unavailable";operation="write_probe_and_copy";proofs=@();actions=@("NETWORK_SHARE_NOT_MOUNTED")},[ordered]@{destination_class="fat32_volume";filesystem="unknown";status="unavailable";operation="write_probe_and_copy";proofs=@();actions=@("NO_MOUNTED_FAT32_DESTINATION_IN_FIXTURE_HOST")})
$receipt=[ordered]@{schema="ld.device.storage03_destination_matrix.receipt.v1";event_type="ld.device.storage03_destination_matrix.receipt.v1";ok=$true;repo_root=$RepoRoot;mode="storage03_destination_matrix_fixture";destructive=$false;writes_source=$false;performs_copy=$true;writes_destination=$true;hashes_file_contents=$true;verified_destination_count=1;blocked_destination_count=3;unavailable_destination_count=2;rows=@($rows);blockers=@();created_utc=[DateTime]::UtcNow.ToString("o")};$outDir=Join-Path $RepoRoot "proofs\receipts\device_storage03_destination_matrix";EnsureDir $outDir;$outPath=Join-Path $outDir ("storage03_destination_matrix_"+[DateTime]::UtcNow.ToString("yyyyMMdd_HHmmss_fff")+".json");Write-Lf $outPath ($receipt|ConvertTo-Json -Depth 100 -Compress);Write-Output("DEVICE_STORAGE03_DESTINATION_MATRIX_PATH: "+$outPath);Write-Output($receipt|ConvertTo-Json -Depth 100 -Compress);Write-Output "LD_DEVICE_STORAGE03_DESTINATION_MATRIX_OK"
