param([Parameter(Mandatory=$true)][string]$RepoRoot)
Set-StrictMode -Version Latest;$ErrorActionPreference="Stop"
function Die([string]$Code,[string]$Detail){throw($Code+":"+$Detail)}
function Require([bool]$Condition,[string]$Code,[string]$Detail){if(-not$Condition){Die $Code $Detail}}
function EnsureDir([string]$Path){if(-not(Test-Path -LiteralPath $Path -PathType Container)){New-Item -ItemType Directory -Force -Path $Path|Out-Null}}
function Write-Lf([string]$Path,[string]$Text){EnsureDir(Split-Path -Parent $Path);$t=($Text-replace"`r`n","`n")-replace"`r","`n";if(-not$t.EndsWith("`n")){$t+="`n"};[IO.File]::WriteAllText($Path,$t,[Text.UTF8Encoding]::new($false))}
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path;. (Join-Path $RepoRoot "scripts\storage\_lib_ld_receipts_v1.ps1")
$base=Join-Path $RepoRoot "proofs\selftest\storage03_resume_idempotency";$allowed=[IO.Path]::GetFullPath((Join-Path $RepoRoot "proofs\selftest")).TrimEnd("\")+"\";$full=[IO.Path]::GetFullPath($base);Require $full.StartsWith($allowed,[StringComparison]::OrdinalIgnoreCase) "FIXTURE_ESCAPE" $full;if(Test-Path -LiteralPath $full){Remove-Item -LiteralPath $full -Recurse -Force};$source=Join-Path $full "source";$prefixDest=Join-Path $full "durable-prefix";$partialDest=Join-Path $full "partial-recovery";EnsureDir $source;EnsureDir $prefixDest;EnsureDir $partialDest
function Put([string]$Rel,[string]$Text){$p=Join-Path $source $Rel;EnsureDir(Split-Path -Parent $p);[IO.File]::WriteAllBytes($p,[Text.Encoding]::UTF8.GetBytes($Text))}
Put "music\one.m4a" "one";Put "music\two.mp3" "two";Put "roms\game.nes" "three";Put "archive\device.cos" "four"
$sourceHashes=@{};foreach($f in @(Get-ChildItem -LiteralPath $source -File -Recurse)){$sourceHashes[$f.FullName]=LDREC-HexSha256File $f.FullName}
function Promote([string]$Rel){$src=Join-Path $source $Rel;$dst=Join-Path $prefixDest $Rel;$tmp=$dst+".legacy-doctor.partial";EnsureDir(Split-Path -Parent $dst);[IO.File]::Copy($src,$tmp,$false);Require ((LDREC-HexSha256File $tmp)-ceq(LDREC-HexSha256File $src)) "PREFIX_HASH" $Rel;[IO.File]::Move($tmp,$dst)}
Promote "music\one.m4a";Promote "music\two.mp3"
$backup=Join-Path $RepoRoot "scripts\media\ld_mounted_media_backup_v1.ps1"
function Run([string]$Dest,[bool]$ExecuteNow){$args=@("-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File",$backup,"-RepoRoot",$RepoRoot,"-SourceRoot",$source,"-DestinationRoot",$Dest,"-MaxFiles","10","-MaxBytes","1048576");if($ExecuteNow){$args+="-Execute"};$out=& powershell.exe @args;if($LASTEXITCODE-ne0){Die "BACKUP_EXIT" ([string]$LASTEXITCODE)};return (LDREC-ReadReceiptFromOutput $out "ld.media.mounted_backup.receipt.v1" (Join-Path $RepoRoot "schemas"))}
$resumed=Run $prefixDest $true;Require ([bool]$resumed.ok) "RESUME_NOT_OK" ([string]$resumed.execution_status);Require ([int]$resumed.duplicate_file_count-eq2) "RESUME_DUPLICATES_BAD" ([string]$resumed.duplicate_file_count);Require ([int]$resumed.copied_file_count-eq2) "RESUME_COPIED_BAD" ([string]$resumed.copied_file_count);Require ([int]$resumed.verified_file_count-eq4) "RESUME_VERIFIED_BAD" ([string]$resumed.verified_file_count)
$stale=Join-Path $partialDest "roms\game.nes.legacy-doctor.partial";EnsureDir(Split-Path -Parent $stale);[IO.File]::WriteAllBytes($stale,[Text.Encoding]::UTF8.GetBytes("interrupted-partial"));$blocked=Run $partialDest $true;Require (-not[bool]$blocked.ok) "STALE_PARTIAL_NOT_BLOCKED" "";Require (@($blocked.blockers)-contains "STALE_PARTIAL_COLLISION") "STALE_PARTIAL_REASON" "";Require (-not(Test-Path -LiteralPath (Join-Path $partialDest "roms\game.nes") -PathType Leaf)) "STALE_PARTIAL_WROTE_FINAL" "";Remove-Item -LiteralPath $stale -Force;$recovered=Run $partialDest $true;Require ([bool]$recovered.ok) "RECOVERY_NOT_OK" ([string]$recovered.execution_status);Require ([int]$recovered.copied_file_count-eq4) "RECOVERY_COPIED_BAD" ([string]$recovered.copied_file_count);$repeat=Run $partialDest $true;Require ([bool]$repeat.ok) "REPEAT_NOT_OK" ([string]$repeat.execution_status);Require ([int]$repeat.duplicate_file_count-eq4) "REPEAT_DUPLICATES_BAD" ([string]$repeat.duplicate_file_count);Require ([int]$repeat.copied_file_count-eq0) "REPEAT_COPIED" ([string]$repeat.copied_file_count)
$sourceUnchanged=$true;foreach($p in @($sourceHashes.Keys)){if((LDREC-HexSha256File $p)-cne[string]$sourceHashes[$p]){$sourceUnchanged=$false}};Require $sourceUnchanged "SOURCE_CHANGED" ""
$receipt=[ordered]@{schema="ld.device.storage03_resume_idempotency.receipt.v1";event_type="ld.device.storage03_resume_idempotency.receipt.v1";ok=$true;repo_root=$RepoRoot;mode="storage03_resume_idempotency_fixture";destructive=$false;writes_source=$false;performs_copy=$true;writes_destination=$true;hashes_file_contents=$true;executor_schema="ld.media.mounted_backup.receipt.v1";durable_prefix_duplicate_count=[int]$resumed.duplicate_file_count;durable_prefix_copied_count=[int]$resumed.copied_file_count;durable_prefix_verified_count=[int]$resumed.verified_file_count;stale_partial_blocked=$true;stale_partial_wrote_final=$false;operator_cleared_partial_for_recovery=$true;recovery_copied_count=[int]$recovered.copied_file_count;repeat_duplicate_count=[int]$repeat.duplicate_file_count;repeat_copied_count=[int]$repeat.copied_file_count;source_unchanged=[bool]$sourceUnchanged;tests=@([ordered]@{name="durable_prefix_resume";passed=$true},[ordered]@{name="stale_partial_fail_closed";passed=$true},[ordered]@{name="operator_cleared_recovery";passed=$true},[ordered]@{name="repeat_idempotency";passed=$true},[ordered]@{name="source_unchanged";passed=$sourceUnchanged});blockers=@("automatic stale-partial deletion is intentionally not performed");created_utc=[DateTime]::UtcNow.ToString("o")};$outDir=Join-Path $RepoRoot "proofs\receipts\device_storage03_resume_idempotency";EnsureDir $outDir;$outPath=Join-Path $outDir ("storage03_resume_idempotency_"+[DateTime]::UtcNow.ToString("yyyyMMdd_HHmmss_fff")+".json");Write-Lf $outPath ($receipt|ConvertTo-Json -Depth 100 -Compress);Write-Output("DEVICE_STORAGE03_RESUME_IDEMPOTENCY_PATH: "+$outPath);Write-Output($receipt|ConvertTo-Json -Depth 100 -Compress);Write-Output "LD_DEVICE_STORAGE03_RESUME_IDEMPOTENCY_OK"
